import base64
import json
import os
import pprint
import shutil
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Optional, List

import boto3
from botocore.exceptions import BotoCoreError, NoCredentialsError

import settings
from erieiron_common import common
from erieiron_common.enums import LlmMessageType, PubSubMessageType
from erieiron_common.llm_apis import llm_interface
from erieiron_common.llm_apis.llm_interface import LlmMessage
from erieiron_common.message_queue.pubsub_manager import PubSubManager
from erieiron_common.models import Business


class PermissionEscalationRequired(Exception):
    """
    Raised when an operation requires elevated IAM permissions that are not currently granted.

    This exception is used to signal that a task must pause and request additional privileges
    (typically via IAM policy updates or trust policy changes) before proceeding.

    Attributes:
        action (str): The AWS action that was attempted (e.g., 'ecr:CreateRepository').
        resource (str): The ARN or wildcard of the resource involved in the attempted action.
    """

    def __init__(self, action: str, resource: str):
        super().__init__(f"Permission escalation required: {action} on {resource}")
        self.action = action
        self.resource = resource


class CommandExecutionError(Exception):
    """
    Raised when a shell command executed by the system fails to complete successfully.

    This error wraps the failure reason and optionally the original exception raised
    by the underlying `subprocess` module.

    Attributes:
        message (str): A description of the error or failed command.
        original_exception (Optional[Exception]): The exception that was raised, if available.
    """

    def __init__(self, message: str, original_exception: Optional[Exception] = None):
        super().__init__(f"{message}. Original exception: {original_exception}")
        self.message = f"{message}. Original exception: {original_exception}"
        self.original_exception = original_exception


def debug_payload(payload):
    """
    Pretty-prints the provided payload using Python's built-in pprint module.

    This function is primarily intended for debugging purposes to visually inspect
    the contents of nested or complex data structures in a human-readable format.

    Args:
        payload (Any): The object or data structure to be printed. Can be any Python object,
                       including dictionaries, lists, or custom class instances.

    Returns:
        None
    """
    pprint.pprint(payload)


def llm_chat_text_response(task_id: str, messages: list[tuple[str, str]]) -> str:
    """
    Sends a sequence of structured messages to the language model and returns a raw text response.

    Args:
        task_id (str): The ID of the task this chat is associated with (used for logging and budget tracking).
        messages (list[tuple[str, str]]): A list of (message_type, message_text) tuples, where message_type
                                          must be one of "system", "assistant", or "user".

    Returns:
        str: The raw text response generated by the language model.

    Raises:
        Exception: If an invalid message_type is encountered.
    """

    llm_messages = []
    for message_type, message_text in messages:
        llm_message_type = LlmMessageType.valid_or(message_type.lower())

        if not llm_message_type:
            raise Exception(f"{message_type} is not a valid message_type.  must be one of [system | assistant | user]")

        llm_messages.append(
            LlmMessage(llm_message_type, message_text or "")
        )

    llm_response = llm_interface.chat(llm_messages)

    if "pytest" not in sys.modules:
        PubSubManager.publish(
            PubSubMessageType.TASK_SPEND,
            task_id,
            {
                "task_id": task_id,
                "usd_spent": llm_response.price_total
            }
        )

    return llm_response.text


def llm_chat_json_response(task_id: str, messages: list[tuple[str, str]]) -> dict:
    """
    Sends a sequence of structured messages to the language model and returns a JSON-parsed response.

    Args:
        task_id (str): The ID of the task this chat is associated with (used for logging and budget tracking).
        messages (list[tuple[str, str]]): A list of (message_type, message_text) tuples, where message_type
                                          must be one of "system", "assistant", or "user".

    Returns:
        dict: The JSON response from the language model, parsed into a Python dictionary.

    Raises:
        Exception: If an invalid message_type is encountered.
    """

    llm_messages = []
    for message_type, message_text in messages:
        llm_message_type = LlmMessageType.valid_or(message_type.lower())

        if not llm_message_type:
            raise Exception(f"{message_type} is not a valid message_type.  must be one of [system | assistant | user]")

        llm_messages.append(
            LlmMessage(llm_message_type, message_text or "")
        )

    llm_response = llm_interface.chat(llm_messages, code_response=True)

    if "pytest" not in sys.modules:
        PubSubManager.publish(
            PubSubMessageType.TASK_SPEND,
            task_id,
            {
                "task_id": task_id,
                "usd_spent": llm_response.price_total
            }
        )

    return llm_response.json()


def get_boto3_client(
        service: str,
        region: str = "us-west-2",
        role_arn_to_assume: Optional[str] = None,
        role_session_name: str = "ErieIronSession",
) -> "boto3.client":
    """
    Creates and returns a boto3 client for the specified AWS service and region.
    Optionally assumes an IAM role before creating the client.

    Args:
        service (str): The AWS service name (e.g., "s3", "ecs", "lambda").
        region (str, optional): AWS region name. Defaults to "us-west-2".
        role_arn_to_assume (Optional[str], optional): If provided, assume this role before creating the client.
        role_session_name (str, optional): The session name to use when assuming the role.

    Returns:
        boto3.client: A configured client object for the specified AWS service.

    Raises:
        RuntimeError: If no valid AWS credentials are found or the client initialization fails.
    """
    try:
        session = boto3.Session()
        credentials = session.get_credentials()
        if not credentials or not credentials.access_key or not credentials.secret_key:
            raise RuntimeError("No valid AWS credentials found. Please configure your AWS credentials.")
        if role_arn_to_assume:
            import botocore
            sts_client = session.client("sts", region_name=region)
            try:
                response = sts_client.assume_role(
                    RoleArn=role_arn_to_assume,
                    RoleSessionName=role_session_name,
                )
            except botocore.exceptions.ClientError as e:
                message = str(e)
                if "not authorized to perform: sts:AssumeRole" in message:
                    current_arn = aws_iam_get_current_user()
                    role_name = role_arn_to_assume.split("/")[-1]
                    print(f"[🔁] Attempting to patch trust policy for role {role_name} to allow {current_arn}")
                    iam_update_trust_policy(role_name, current_arn)
                    # retry once
                    response = sts_client.assume_role(
                        RoleArn=role_arn_to_assume,
                        RoleSessionName=role_session_name,
                    )
                else:
                    raise

            assumed_creds = response["Credentials"]
            return boto3.client(
                service,
                region_name=region,
                aws_access_key_id=assumed_creds["AccessKeyId"],
                aws_secret_access_key=assumed_creds["SecretAccessKey"],
                aws_session_token=assumed_creds["SessionToken"],
            )
        return session.client(service, region_name=region)
    except (BotoCoreError, NoCredentialsError) as e:
        raise RuntimeError(f"Failed to create boto3 client for {service}: {e}")


def aws_cli(business_id: uuid.UUID, command: list[str], input_data: str | None = None) -> str:
    """
    Executes an AWS CLI command within the business's sandbox context.

    The command is validated to ensure all filesystem-related arguments stay within
    the business's sandbox directory. The command is executed as a subprocess,
    with optional input piped to its stdin.

    Args:
        business_id (uuid.UUID): Unique ID of the business issuing the command.
        command (list[str]): AWS CLI command and arguments (e.g., ["s3", "ls"]).
        input_data (str | None): Optional string to pass to stdin.

    Returns:
        str: Trimmed stdout output from the command.

    Raises:
        CommandExecutionError: If the command fails or violates sandbox constraints.
    """
    full_cmd = ["aws"] + command
    return run_shell_command(business_id, full_cmd, input_data=input_data)


def aws_ecr_login(business_id: uuid.UUID, aws_region: str, aws_account_id: str) -> None:
    """
    Authenticates Docker with AWS Elastic Container Registry (ECR).

    This function first retrieves an ECR login password using the AWS CLI,
    then logs Docker into the ECR registry for the specified AWS account and region.
    All shell commands are sandboxed using the business's designated directory.

    Args:
        business_id (uuid.UUID): Unique ID of the business performing the login.
        aws_region (str): AWS region for the ECR registry (e.g., "us-west-2").
        aws_account_id (str): AWS account ID hosting the ECR registry.

    Raises:
        CommandExecutionError: If retrieving the ECR login password or the Docker login fails.
    """
    password = aws_cli(business_id, ["ecr", "get-login-password", "--region", aws_region])
    print("retrieved aws ecr login password")

    docker_login_cmd = [
        "docker", "login",
        "--username", "AWS",
        "--password-stdin",
        f"{aws_account_id}.dkr.ecr.{aws_region}.amazonaws.com",
    ]
    run_shell_command(business_id, docker_login_cmd, input_data=password)
    print("docker login successful")


def run_shell_command(business_id: uuid.UUID, command: List[str], input_data: Optional[str] = None) -> str:
    """
    Executes a shell command and captures its output.

    Parameters:
        business_id (uuid): The id of the Business issuing this command
        command (List[str]): The command to run, provided as a list of arguments.
        input_data (Optional[str]): Optional string data to pass to the command's standard input.

    Returns:
        str: The trimmed standard output of the command if it executes successfully.

    Raises:
        CommandExecutionError: If the command exits with a non-zero status or if a subprocess error occurs.

    If `sandbox_path` is provided, any command argument that appears to be a path will be checked
    to ensure it remains within the sandbox directory. If a path is detected outside the sandbox,
    the command will be blocked and a CommandExecutionError raised.
    """

    if not (command[0] == "docker" or command[0] == "aws"):
        sandbox_path = Business.objects.get(id=business_id).get_sandbox_dir()
        for arg in command[1:]:
            if os.path.isabs(arg) or os.path.exists(arg) or "/" in arg:
                common.assert_in_sandbox(sandbox_path, arg)

    try:
        print("executing command:", " ".join(command))
        result = subprocess.run(
            command,
            input=input_data.encode("utf-8") if input_data is not None else None,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise CommandExecutionError(
                f"command '{' '.join(command)}' failed with return code {result.returncode}. stdout: {result.stdout.strip()} stderr: {result.stderr.strip()}"
            )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        raise CommandExecutionError(f"command '{' '.join(command)}' failed", e)


def get_aws_metadata() -> dict:
    """
    Returns a dictionary containing the AWS account metadata used by the application.

    This includes the AWS account ID and default region, as defined in the application settings.

    Returns:
        dict: A dictionary with the following keys:
            - "aws_account_id" (str): The AWS account identifier.
            - "aws_region" (str): The default AWS region (e.g., "us-west-2").

    Example:
        >>> get_aws_metadata()
        {'aws_account_id': '123456789012', 'aws_region': 'us-west-2'}
    """
    return {
        "aws_account_id": settings.AWS_ACCOUNT_ID,
        "aws_region": settings.AWS_DEFAULT_REGION_NAME
    }


# --- IAM and permission escalation utilities ---


def extract_action_from_error(error: Exception) -> str:
    """
    Attempts to extract the missing IAM action from an AWS AccessDenied error message.

    Args:
        error (Exception): The exception raised during AWS operation.

    Returns:
        str: The missing IAM action, if detectable; otherwise 'unknown'.
    """
    message = str(error)
    # Simplified pattern matching, can be extended with regex if needed
    if "ecr:GetAuthorizationToken" in message:
        return "ecr:GetAuthorizationToken"
    return "unknown"


def infer_resource_from_context() -> str:
    """
    Provides a generic resource ARN based on the current AWS context.

    Returns:
        str: A guessed resource ARN, defaulting to wildcard if not determinable.
    """
    try:
        meta = get_aws_metadata()
        return f"arn:aws:ecr:{meta['aws_region']}:{meta['aws_account_id']}:repository/*"
    except Exception:
        return "*"


def aws_iam_get_current_user() -> str:
    """
    Retrieves the current AWS IAM user or role making requests.

    Returns:
        str: The IAM user or role ARN.

    Raises:
        RuntimeError: If the IAM caller identity cannot be determined.
    """
    try:
        client = get_boto3_client("sts")
        identity = client.get_caller_identity()
        return identity["Arn"]
    except Exception as e:
        raise RuntimeError(f"Failed to retrieve IAM caller identity: {e}")


def iam_propose_policy_patch(business_id: uuid.UUID, actions: list[str], resources: list[str], reason: str) -> None:
    """
    Updates or creates a least-privilege IAM policy inline to the specified IAM role or user.
    If the policy already exists, it merges the new statement without duplicating.

    Args:
        business_id (uuid.UUID): Unique ID of the business issuing the command.
        actions (list[str]): IAM actions to grant.
        resources (list[str]): Resources these actions apply to.
        reason (str): Justification for this permission grant.

    Raises:
        RuntimeError: If the IAM policy application fails.
    """

    business = Business.objects.get(id=business_id)
    iam_role_name = business.get_iam_role_name()
    print("[IAM POLICY PATCH REQUEST]")
    print(f"IAM Role Name: {iam_role_name}")
    print(f"Actions: {actions}")
    print(f"Resources: {resources}")
    print(f"Reason: {reason}")

    iam_client = get_boto3_client("iam")
    policy_name = f"{iam_role_name}-inline"

    try:
        get_policy = lambda: iam_client.get_role_policy(RoleName=iam_role_name, PolicyName=policy_name)
        put_policy = lambda doc: iam_client.put_role_policy(
            RoleName=iam_role_name,
            PolicyName=policy_name,
            PolicyDocument=doc
        )

        try:
            existing_policy = get_policy()
            policy_document_item = existing_policy["PolicyDocument"]
            if isinstance(policy_document_item, str):
                doc = json.loads(policy_document_item)
            elif isinstance(policy_document_item, dict):
                doc = policy_document_item
            else:
                raise TypeError(f"PolicyDocument has unexpected type: {type(policy_document_item)}")
            # Merge new statement, avoid duplicates
            new_statement = {
                "Effect": "Allow",
                "Action": actions,
                "Resource": resources
            }

            # Check if similar statement exists
            def actions_equal(a1, a2):
                if isinstance(a1, list) and isinstance(a2, list):
                    return set(a1) == set(a2)
                return a1 == a2

            def resources_equal(r1, r2):
                if isinstance(r1, list) and isinstance(r2, list):
                    return set(r1) == set(r2)
                return r1 == r2

            # Only append if no existing statement has same actions and resources
            if not any(
                    s.get("Effect") == "Allow" and
                    actions_equal(s.get("Action", []), new_statement["Action"]) and
                    resources_equal(s.get("Resource", []), new_statement["Resource"])
                    for s in doc.get("Statement", [])
            ):
                doc["Statement"].append(new_statement)
        except iam_client.exceptions.NoSuchEntityException:
            doc = {
                "Version": "2012-10-17",
                "Statement": [{
                    "Effect": "Allow",
                    "Action": actions,
                    "Resource": resources
                }]
            }

        put_policy(json.dumps(doc))
        print(f"[✅] Policy merged/applied to: {iam_role_name}")
    except Exception as e:
        raise RuntimeError(f"Failed to update IAM policy patch on '{iam_role_name}': {e}")


def iam_update_trust_policy(role_name: str, trusted_principal_arn: str) -> None:
    """
    Ensures the specified role's trust policy allows the given principal to assume it.

    Args:
        role_name (str): The name of the IAM role to update.
        trusted_principal_arn (str): The ARN of the user or role that should be allowed to assume it.

    Raises:
        RuntimeError: If the trust policy cannot be updated.
    """
    iam_client = get_boto3_client("iam")

    trust_policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Effect": "Allow",
            "Principal": {"AWS": trusted_principal_arn},
            "Action": "sts:AssumeRole"
        }]
    }

    try:
        iam_client.update_assume_role_policy(
            RoleName=role_name,
            PolicyDocument=json.dumps(trust_policy)
        )
        print(f"[✅] Updated trust policy for role: {role_name}")
    except Exception as e:
        raise RuntimeError(f"Failed to update trust policy for role '{role_name}': {e}")


def build_and_push_dev_container(
        business_id: uuid.UUID,
        dockerfile: Path,
        image_tag: str = "latest"
) -> str:
    """
    Builds a Docker development container image, pushes it to AWS Elastic Container Registry (ECR),
    and returns the image URI.

    This function performs the following steps:
      1. Retrieves AWS/ECR metadata and IAM role information for the business.
      2. Ensures the target ECR repository exists (creating it if necessary).
      3. Authenticates Docker with ECR using a temporary token.
      4. Builds the Docker image from the provided Dockerfile content and context directory.
      5. Tags and pushes the image to ECR.
      6. Verifies the image is available in ECR, and returns its full URI.

    If permissions are missing at any step, the function attempts to escalate or propose new IAM policies,
    and raises a PermissionEscalationRequired exception with details.

    Args:
        business_id (uuid.UUID): The unique identifier of the business context for which the image is being built.
        dockerfile (Path): The Dockerfile to use for building the image.
        image_tag (str, optional): The tag to use for the Docker image (default is "latest").

    Returns:
        str: The full URI of the pushed Docker image in ECR.

    Raises:
        PermissionEscalationRequired: If the operation requires additional AWS permissions or a trust policy update.
        CommandExecutionError: If a shell command for Docker or AWS CLI fails.
        RuntimeError: For unrecoverable errors with AWS API calls or IAM operations.
        Exception: For any other unexpected errors encountered during the process.
    """
    dockerfile = common.assert_exists(dockerfile)

    business = Business.objects.get(id=business_id)
    iam_role_name = business.get_iam_role_name()
    repo_name = business.service_token

    aws_metadata = get_aws_metadata()
    aws_account_id = aws_metadata["aws_account_id"]
    aws_region = aws_metadata["aws_region"]

    role_arn = f"arn:aws:iam::{aws_account_id}:role/{iam_role_name}"
    repository_arn = f"arn:aws:ecr:{aws_region}:{aws_account_id}:repository/{repo_name}"
    image_uri = f"{aws_account_id}.dkr.ecr.{aws_region}.amazonaws.com/{repo_name}:{image_tag}"

    try:
        ecr_client = get_boto3_client("ecr", region=aws_region, role_arn_to_assume=role_arn)
    except Exception:
        current_user_arn = aws_iam_get_current_user()
        iam_update_trust_policy(role_name=iam_role_name, trusted_principal_arn=current_user_arn)
        raise PermissionEscalationRequired("sts:AssumeRole", role_arn)

    try:
        ecr_client.describe_repositories(repositoryNames=[repo_name])
    except Exception as e:
        if "RepositoryNotFoundException" in str(e):
            try:
                ecr_client.create_repository(
                    repositoryName=repo_name,
                    tags=[{"Key": "Service", "Value": repo_name}]
                )
            except Exception as ce:
                if "AccessDenied" in str(ce):
                    iam_propose_policy_patch(
                        business_id, ["ecr:CreateRepository"], [repository_arn],
                        reason=f"To create ECR repository {repo_name}"
                    )
                    raise PermissionEscalationRequired("ecr:CreateRepository", repository_arn)
                raise
        elif "AccessDenied" in str(e):
            iam_propose_policy_patch(
                business_id, ["ecr:DescribeRepositories"], [repository_arn],
                reason=f"To describe ECR repository {repo_name}"
            )
            raise PermissionEscalationRequired("ecr:DescribeRepositories", repository_arn)
        raise

    try:
        auth_data = ecr_client.get_authorization_token()["authorizationData"][0]
        token = base64.b64decode(auth_data["authorizationToken"]).decode("utf-8")
        username, password = token.split(":", 1)
        proxy_endpoint = auth_data["proxyEndpoint"]
        run_shell_command(business_id, ["docker", "login", "-u", username, "-p", password, proxy_endpoint])
    except Exception as ce:
        if "AccessDenied" in str(ce):
            iam_propose_policy_patch(
                business_id, ["ecr:GetAuthorizationToken"], ["*"],
                reason="To allow Docker login to ECR"
            )
            raise PermissionEscalationRequired("ecr:GetAuthorizationToken", "*")
        raise

    build_context_path_str = str(dockerfile.parent)
    run_shell_command(
        business_id,
        ["docker", "build", "-f", str(dockerfile), "-t", f"{repo_name}:{image_tag}", build_context_path_str]
    )
    run_shell_command(
        business_id,
        ["docker", "tag", f"{repo_name}:{image_tag}", image_uri]
    )

    try:
        run_shell_command(business_id, ["docker", "push", image_uri])
    except CommandExecutionError as ce:
        push_actions = [
            "ecr:BatchCheckLayerAvailability",
            "ecr:CompleteLayerUpload",
            "ecr:InitiateLayerUpload",
            "ecr:PutImage",
            "ecr:UploadLayerPart",
        ]
        iam_propose_policy_patch(
            business_id, push_actions, [repository_arn],
            reason="To allow push to ECR repository"
        )
        raise PermissionEscalationRequired(", ".join(push_actions), repository_arn)

    try:
        ecr_client.batch_get_image(
            repositoryName=repo_name, imageIds=[{"imageTag": image_tag}]
        )
    except Exception as e:
        if "AccessDenied" in str(e):
            iam_propose_policy_patch(
                business_id, ["ecr:BatchGetImage"], [repository_arn],
                reason="To verify image in ECR"
            )
            raise PermissionEscalationRequired("ecr:BatchGetImage", repository_arn)
        raise

    return image_uri


def clone_template_project_to_sandbox(business_id: uuid.UUID) -> Path:
    """
    Clones the template project into the business's sandbox directory.

    This is used to bootstrap a new web service or containerized project environment for a business.

    Args:
        business_id (uuid.UUID): The UUID of the business for which the project should be cloned.

    Returns:
        Path: The path to the newly created project directory inside the business sandbox.

    Raises:
        FileNotFoundError: If the template source directory does not exist.
        Exception: If the copy operation fails for any reason.
    """
    template_dir = Path(__file__).parent / "bootstrap_webservice_container"
    if not template_dir.exists():
        raise FileNotFoundError(f"Template directory not found at {template_dir}")

    business = Business.objects.get(id=business_id)
    sandbox_dir = Path(business.get_sandbox_dir())
    destination_dir = sandbox_dir / "webservice"

    common.copy_missing_files(template_dir, destination_dir)

    return destination_dir

