import base64
import json
import os
import pprint
import shutil
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Optional, List
import boto3
from botocore.exceptions import BotoCoreError, NoCredentialsError
import settings
from erieiron_common import common
from erieiron_common.enums import LlmMessageType, PubSubMessageType
from erieiron_common.llm_apis import llm_interface
from erieiron_common.llm_apis.llm_interface import LlmMessage
from erieiron_common.message_queue.pubsub_manager import PubSubManager
from erieiron_common.models import Business

class PermissionEscalationRequired(Exception):
    """Raised when an operation requires elevated IAM permissions that are not currently granted.

This exception is used to signal that a task must pause and request additional privileges
(typically via IAM policy updates or trust policy changes) before proceeding.

Attributes:
    action (str): The AWS action that was attempted (e.g., 'ecr:CreateRepository').
    resource (str): The ARN or wildcard of the resource involved in the attempted action."""
    def __init__(self, action: str, resource: str):
        pass

class CommandExecutionError(Exception):
    """Raised when a shell command executed by the system fails to complete successfully.

This error wraps the failure reason and optionally the original exception raised
by the underlying `subprocess` module.

Attributes:
    message (str): A description of the error or failed command.
    original_exception (Optional[Exception]): The exception that was raised, if available."""
    def __init__(self, message: str, original_exception: Optional[Exception]=None):
        pass

def debug_payload(payload):
    """Pretty-prints the provided payload using Python's built-in pprint module.

This function is primarily intended for debugging purposes to visually inspect
the contents of nested or complex data structures in a human-readable format.

Args:
    payload (Any): The object or data structure to be printed. Can be any Python object,
                   including dictionaries, lists, or custom class instances.

Returns:
    None"""
    pass

def llm_chat_text_response(task_id: str, messages: list[tuple[str, str]]) -> str:
    """Sends a sequence of structured messages to the language model and returns a raw text response.

Args:
    task_id (str): The ID of the task this chat is associated with (used for logging and budget tracking).
    messages (list[tuple[str, str]]): A list of (message_type, message_text) tuples, where message_type
                                      must be one of "system", "assistant", or "user".

Returns:
    str: The raw text response generated by the language model.

Raises:
    Exception: If an invalid message_type is encountered."""
    pass

def llm_chat_json_response(task_id: str, messages: list[tuple[str, str]]) -> dict:
    """Sends a sequence of structured messages to the language model and returns a JSON-parsed response.

Args:
    task_id (str): The ID of the task this chat is associated with (used for logging and budget tracking).
    messages (list[tuple[str, str]]): A list of (message_type, message_text) tuples, where message_type
                                      must be one of "system", "assistant", or "user".

Returns:
    dict: The JSON response from the language model, parsed into a Python dictionary.

Raises:
    Exception: If an invalid message_type is encountered."""
    pass

def get_boto3_client(service: str, region: str='us-west-2', role_arn_to_assume: Optional[str]=None, role_session_name: str='ErieIronSession') -> 'boto3.client':
    """Creates and returns a boto3 client for the specified AWS service and region.
Optionally assumes an IAM role before creating the client.

Args:
    service (str): The AWS service name (e.g., "s3", "ecs", "lambda").
    region (str, optional): AWS region name. Defaults to "us-west-2".
    role_arn_to_assume (Optional[str], optional): If provided, assume this role before creating the client.
    role_session_name (str, optional): The session name to use when assuming the role.

Returns:
    boto3.client: A configured client object for the specified AWS service.

Raises:
    RuntimeError: If no valid AWS credentials are found or the client initialization fails."""
    pass

def aws_cli(business_id: uuid.UUID, command: list[str], input_data: str | None=None) -> str:
    """Executes an AWS CLI command within the business's sandbox context.

The command is validated to ensure all filesystem-related arguments stay within
the business's sandbox directory. The command is executed as a subprocess,
with optional input piped to its stdin.

Args:
    business_id (uuid.UUID): Unique ID of the business issuing the command.
    command (list[str]): AWS CLI command and arguments (e.g., ["s3", "ls"]).
    input_data (str | None): Optional string to pass to stdin.

Returns:
    str: Trimmed stdout output from the command.

Raises:
    CommandExecutionError: If the command fails or violates sandbox constraints."""
    pass

def aws_ecr_login(business_id: uuid.UUID, aws_region: str, aws_account_id: str) -> None:
    """Authenticates Docker with AWS Elastic Container Registry (ECR).

This function first retrieves an ECR login password using the AWS CLI,
then logs Docker into the ECR registry for the specified AWS account and region.
All shell commands are sandboxed using the business's designated directory.

Args:
    business_id (uuid.UUID): Unique ID of the business performing the login.
    aws_region (str): AWS region for the ECR registry (e.g., "us-west-2").
    aws_account_id (str): AWS account ID hosting the ECR registry.

Raises:
    CommandExecutionError: If retrieving the ECR login password or the Docker login fails."""
    pass

def run_shell_command(business_id: uuid.UUID, command: List[str], input_data: Optional[str]=None) -> str:
    """Executes a shell command and captures its output.

Parameters:
    business_id (uuid): The id of the Business issuing this command
    command (List[str]): The command to run, provided as a list of arguments.
    input_data (Optional[str]): Optional string data to pass to the command's standard input.

Returns:
    str: The trimmed standard output of the command if it executes successfully.

Raises:
    CommandExecutionError: If the command exits with a non-zero status or if a subprocess error occurs.

If `sandbox_path` is provided, any command argument that appears to be a path will be checked
to ensure it remains within the sandbox directory. If a path is detected outside the sandbox,
the command will be blocked and a CommandExecutionError raised."""
    pass

def get_aws_metadata() -> dict:
    """Returns a dictionary containing the AWS account metadata used by the application.

This includes the AWS account ID and default region, as defined in the application settings.

Returns:
    dict: A dictionary with the following keys:
        - "aws_account_id" (str): The AWS account identifier.
        - "aws_region" (str): The default AWS region (e.g., "us-west-2").

Example:
    >>> get_aws_metadata()
    {'aws_account_id': '123456789012', 'aws_region': 'us-west-2'}"""
    pass

def extract_action_from_error(error: Exception) -> str:
    """Attempts to extract the missing IAM action from an AWS AccessDenied error message.

Args:
    error (Exception): The exception raised during AWS operation.

Returns:
    str: The missing IAM action, if detectable; otherwise 'unknown'."""
    pass

def infer_resource_from_context() -> str:
    """Provides a generic resource ARN based on the current AWS context.

Returns:
    str: A guessed resource ARN, defaulting to wildcard if not determinable."""
    pass

def aws_iam_get_current_user() -> str:
    """Retrieves the current AWS IAM user or role making requests.

Returns:
    str: The IAM user or role ARN.

Raises:
    RuntimeError: If the IAM caller identity cannot be determined."""
    pass

def iam_propose_policy_patch(business_id: uuid.UUID, actions: list[str], resources: list[str], reason: str) -> None:
    """Updates or creates a least-privilege IAM policy inline to the specified IAM role or user.
If the policy already exists, it merges the new statement without duplicating.

Args:
    business_id (uuid.UUID): Unique ID of the business issuing the command.
    actions (list[str]): IAM actions to grant.
    resources (list[str]): Resources these actions apply to.
    reason (str): Justification for this permission grant.

Raises:
    RuntimeError: If the IAM policy application fails."""
    pass

def iam_update_trust_policy(role_name: str, trusted_principal_arn: str) -> None:
    """Ensures the specified role's trust policy allows the given principal to assume it.

Args:
    role_name (str): The name of the IAM role to update.
    trusted_principal_arn (str): The ARN of the user or role that should be allowed to assume it.

Raises:
    RuntimeError: If the trust policy cannot be updated."""
    pass

def build_and_push_dev_container(business_id: uuid.UUID, dockerfile: Path, image_tag: str='latest') -> str:
    """Builds a Docker development container image, pushes it to AWS Elastic Container Registry (ECR),
and returns the image URI.

This function performs the following steps:
  1. Retrieves AWS/ECR metadata and IAM role information for the business.
  2. Ensures the target ECR repository exists (creating it if necessary).
  3. Authenticates Docker with ECR using a temporary token.
  4. Builds the Docker image from the provided Dockerfile content and context directory.
  5. Tags and pushes the image to ECR.
  6. Verifies the image is available in ECR, and returns its full URI.

If permissions are missing at any step, the function attempts to escalate or propose new IAM policies,
and raises a PermissionEscalationRequired exception with details.

Args:
    business_id (uuid.UUID): The unique identifier of the business context for which the image is being built.
    dockerfile (Path): The Dockerfile to use for building the image.
    image_tag (str, optional): The tag to use for the Docker image (default is "latest").

Returns:
    str: The full URI of the pushed Docker image in ECR.

Raises:
    PermissionEscalationRequired: If the operation requires additional AWS permissions or a trust policy update.
    CommandExecutionError: If a shell command for Docker or AWS CLI fails.
    RuntimeError: For unrecoverable errors with AWS API calls or IAM operations.
    Exception: For any other unexpected errors encountered during the process."""
    pass

def clone_template_project_to_sandbox(business_id: uuid.UUID) -> Path:
    """Clones the template project into the business's sandbox directory.

This is used to bootstrap a new web service or containerized project environment for a business.

Args:
    business_id (uuid.UUID): The UUID of the business for which the project should be cloned.

Returns:
    Path: The path to the newly created project directory inside the business sandbox.

Raises:
    FileNotFoundError: If the template source directory does not exist.
    Exception: If the copy operation fails for any reason."""
    pass