import json
import os
import sys
from functools import lru_cache

import boto3
from botocore.exceptions import ClientError

from erieiron_common.enums import LlmMessageType, PubSubMessageType
from erieiron_common.llm_apis import llm_interface
from erieiron_common.llm_apis.llm_interface import LlmMessage
from erieiron_common.message_queue.pubsub_manager import PubSubManager


@lru_cache(maxsize=1)
def get_secret_json(secret_arn: str) -> dict:
    """Fetch and parse a JSON secret from AWS Secrets Manager. Fails fast on errors."""
    client = boto3.client("secretsmanager")  # Region from env/IMDS unless overridden elsewhere
    try:
        resp = client.get_secret_value(SecretId=secret_arn)
    except ClientError as e:
        raise RuntimeError(f"Failed to fetch RDS secret {secret_arn}: {e}") from e
    
    secret_str = resp.get("SecretString")
    if not secret_str:
        raise RuntimeError(f"Secret {secret_arn} returned empty SecretString")
    
    try:
        data = json.loads(secret_str)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"Secret {secret_arn} is not valid JSON: {e}") from e
    
    required_keys = ["username", "password", "host", "port", "database"]
    missing = [k for k in required_keys if k not in data]
    if missing:
        raise RuntimeError(f"Secret {secret_arn} missing keys: {missing}")
    
    return data


def get_secret_from_env_arn(env_var_name):
    secret_arn = os.getenv(env_var_name)
    if not secret_arn:
        raise ValueError(f"no env var found for {env_var_name}")
    
    secret_json = get_secret_json(secret_arn)
    if not secret_json:
        raise ValueError(f"no secret data found for {secret_arn}")
    
    return secret_json


def llm_chat_text_response(task_id: str, messages: list[tuple[str, str]]) -> str:
    """
    Sends a sequence of structured messages to the language model and returns a raw text response.

    Args:
        task_id (str): The ID of the task this chat is associated with (used for logging and budget tracking).
        messages (list[tuple[str, str]]): A list of (message_type, message_text) tuples, where message_type
                                          must be one of "system", "assistant", or "user".

    Returns:
        str: The raw text response generated by the language model.

    Raises:
        Exception: If an invalid message_type is encountered.
    """
    
    llm_messages = []
    for message_type, message_text in messages:
        llm_message_type = LlmMessageType.valid_or(message_type.lower())
        
        if not llm_message_type:
            raise Exception(f"{message_type} is not a valid message_type.  must be one of [system | assistant | user]")
        
        llm_messages.append(
            LlmMessage(llm_message_type, message_text or "")
        )
    
    llm_response = llm_interface.chat(llm_messages)
    
    if "pytest" not in sys.modules:
        PubSubManager.publish(
            PubSubMessageType.TASK_SPEND,
            task_id,
            {
                "task_id": task_id,
                "usd_spent": llm_response.price_total
            }
        )
    
    return llm_response.text


def llm_chat_json_response(task_id: str, messages: list[tuple[str, str]]) -> dict:
    """
    Sends a sequence of structured messages to the language model and returns a JSON-parsed response.

    Args:
        task_id (str): The ID of the task this chat is associated with (used for logging and budget tracking).
        messages (list[tuple[str, str]]): A list of (message_type, message_text) tuples, where message_type
                                          must be one of "system", "assistant", or "user".

    Returns:
        dict: The JSON response from the language model, parsed into a Python dictionary.

    Raises:
        Exception: If an invalid message_type is encountered.
    """
    
    llm_messages = []
    for message_type, message_text in messages:
        llm_message_type = LlmMessageType.valid_or(message_type.lower())
        
        if not llm_message_type:
            raise Exception(f"{message_type} is not a valid message_type.  must be one of [system | assistant | user]")
        
        llm_messages.append(
            LlmMessage(llm_message_type, message_text or "")
        )
    
    llm_response = llm_interface.chat(llm_messages, code_response=True)
    
    if "pytest" not in sys.modules:
        PubSubManager.publish(
            PubSubMessageType.TASK_SPEND,
            task_id,
            {
                "task_id": task_id,
                "usd_spent": llm_response.price_total
            }
        )
    
    return llm_response.json()
