version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting CloudFormation deploy"
  build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy --template-file aws/cloudformation/runtime_environment.yml --stack-name erieiron-infra-prod --capabilities CAPABILITY_NAMED_IAM --parameter-overrides EnvironmentName=prod

artifacts:
  files: []
