version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - set -e
      - >
        docker build -f Dockerfile.webservice.base
        --build-arg ERIELAB_ENV=$ERIELAB_ENV
        --build-arg COMMIT_ID=$COMMIT_ID
        -t erielab-webservice-basecontainer:$COMMIT_ID
        -t erielab-webservice-basecontainer:latest
        .
      - docker tag erielab-webservice-basecontainer:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/erielab-webservice-basecontainer:latest
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/erielab-webservice-basecontainer:latest
      - printf '[{"name":"erielab-webservice-basecontainer-container","imageUri":"%s.dkr.ecr.%s.amazonaws.com/erielab-webservice-basecontainer:latest"}]' $AWS_ACCOUNT_ID $AWS_REGION > imagedefinitions.json
      - echo '------  imagedefinitions.json ---------'
      - cat imagedefinitions.json
      - echo '---------------------------------------'
artifacts:
  files: imagedefinitions.json