# Generated by Django 5.1.6 on 2025-06-14 03:03

import django.contrib.postgres.search
import django.db.models.deletion
import erieiron_common.enums
import erieiron_common.json_encoder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("sandbox_dir_name", models.TextField()),
                ("summary", models.TextField(null=True)),
                ("raw_idea", models.TextField(null=True)),
                ("bank_account_id", models.TextField(null=True)),
                ("business_plan", models.TextField(null=True)),
                ("value_prop", models.TextField(null=True)),
                ("revenue_model", models.TextField(null=True)),
                ("audience", models.TextField(null=True)),
                ("core_functions", models.JSONField(default=list)),
                ("execution_dependencies", models.JSONField(default=list)),
                ("growth_channels", models.JSONField(default=list)),
                ("personalization_options", models.JSONField(default=list)),
                (
                    "source",
                    models.TextField(
                        choices=[
                            ("HUMAN", "Human"),
                            ("BUSINESS_FINDER_AGENT", "Business finder agent"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("IDEA", "Idea"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("SHUTDOWN", "Shutdown"),
                        ],
                        default=erieiron_common.enums.BusinessStatus["IDEA"],
                    ),
                ),
                ("allow_autonomous_shutdown", models.BooleanField(default=True)),
                (
                    "autonomy_level",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "erieiron_business",
            },
        ),
        migrations.CreateModel(
            name="CacheData",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
                ("val", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CodeFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_path", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "erieiron_codefile",
            },
        ),
        migrations.CreateModel(
            name="DesignComponent",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "erieiron_designcomponent",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cognito_sub",
                    models.UUIDField(db_index=True, null=True, unique=True),
                ),
                ("name", models.TextField(null=True)),
                ("email", models.TextField()),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("BANNED", "Banned"),
                            ("FREE_USER", "Free user"),
                            ("SUBSCRIBER", "Subscriber"),
                            ("SUBSCRIBER_PRO", "Subscriber pro"),
                            ("BETA_USER", "Beta user"),
                            ("ADMIN", "Admin"),
                            ("DEVELOPER", "Developer"),
                            ("SYSTEM", "System"),
                        ],
                        default="FREE_USER",
                    ),
                ),
                ("server_root", models.TextField(null=True)),
                ("last_updated", models.DateTimeField(null=True)),
                (
                    "cookie_consent",
                    models.CharField(
                        blank=True,
                        choices=[("ACCEPTED", "Accepted"), ("DECLINED", "Declined")],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "analytics_cookie_consent",
                    models.CharField(
                        blank=True,
                        choices=[("ACCEPTED", "Accepted"), ("DECLINED", "Declined")],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_person",
            },
        ),
        migrations.CreateModel(
            name="PubSubEnvironment",
            fields=[
                (
                    "id",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
                ("desired_handler_instance_count", models.IntegerField(default=1)),
                (
                    "last_requested_increase",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
            options={
                "db_table": "erieiron_pubsubenvironment",
            },
        ),
        migrations.CreateModel(
            name="PubSubMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("env", models.TextField(db_index=True)),
                ("namespace", models.TextField(db_index=True)),
                ("message_type", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[
                            ("HIGH", "High"),
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                        ],
                        default="NORMAL",
                        null=True,
                    ),
                ),
                ("status", models.TextField()),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("handler_instance_id", models.TextField(db_index=True, null=True)),
                ("retry_count", models.IntegerField(default=1, null=True)),
                ("error_message", models.TextField(null=True)),
                ("message_batch_idx", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "erieiron_pubsubmessage",
            },
        ),
        migrations.CreateModel(
            name="RuntimeConfigVal",
            fields=[
                (
                    "name",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
                ("value", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("business_name", models.TextField()),
                (
                    "estimated_monthly_revenue_at_steady_state_usd",
                    models.FloatField(null=True),
                ),
                ("time_to_profit_estimate_months", models.IntegerField(null=True)),
                ("potential_mode", models.TextField(null=True)),
                ("summary", models.TextField(null=True)),
                ("final_recommendation_justification", models.TextField(null=True)),
                ("final_recommendation_score_1_to_10", models.IntegerField(null=True)),
                (
                    "estimated_operating_total_cost_per_month_usd",
                    models.FloatField(null=True),
                ),
                (
                    "upfront_investment_estimated_amount_usd",
                    models.FloatField(null=True),
                ),
                (
                    "total_addressable_market_estimate_usd_per_year",
                    models.FloatField(null=True),
                ),
                (
                    "total_addressable_market_source_or_rationale",
                    models.TextField(null=True),
                ),
                (
                    "macro_trends_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "risks_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "monthly_expenses_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "potential_competitors_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "use_of_funds_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessanalysis",
            },
        ),
        migrations.CreateModel(
            name="BusinessBankBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessbankbalancesnapshot",
            },
        ),
        migrations.CreateModel(
            name="BusinessBankBalanceSnapshotAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_name", models.TextField()),
                ("account_id", models.TextField()),
                ("available_balance", models.FloatField(null=True)),
                ("current_balance", models.FloatField(null=True)),
                ("status", models.TextField(null=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.businessbankbalancesnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessbankbalancesnapshotaccount",
            },
        ),
        migrations.CreateModel(
            name="BusinessCapacityAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "compute_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "human_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                ("justification", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesscapacityanalysis",
            },
        ),
        migrations.CreateModel(
            name="BusinessCeoDirective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("target_agent", models.TextField()),
                ("directive_summary", models.TextField()),
                ("goal_alignment", models.JSONField(default=list)),
                ("kpi_targets", models.JSONField(default=dict)),
                ("initiative_reference", models.TextField(default="")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessceodirective",
            },
        ),
        migrations.CreateModel(
            name="BusinessGuidance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "guidance",
                    models.TextField(
                        choices=[
                            ("MAINTAIN", "Maintain"),
                            ("INCREASE_BUDGET", "Increase budget"),
                            ("DECREASE_BUDGET", "Decrease budget"),
                            ("SHUTDOWN", "Shutdown"),
                        ]
                    ),
                ),
                ("justification", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessguidance",
            },
        ),
        migrations.CreateModel(
            name="BusinessKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("kpi_id", models.TextField()),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
                ("target_value", models.FloatField()),
                ("unit", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesskpi",
            },
        ),
        migrations.CreateModel(
            name="BusinessGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("goal_id", models.TextField()),
                ("description", models.TextField()),
                ("target_value", models.FloatField()),
                ("unit", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("ON_TRACK", "On track"),
                            ("AT_RISK", "At risk"),
                            ("OFF_TRACK", "Off track"),
                        ]
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessgoal",
            },
        ),
        migrations.CreateModel(
            name="BusinessKPIProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesskpiprogress",
            },
        ),
        migrations.CreateModel(
            name="BusinessLegalAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField()),
                ("justification", models.TextField(null=True)),
                (
                    "required_disclaimers_or_terms",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "risk_rating",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")],
                        null=True,
                    ),
                ),
                (
                    "recommended_entity_structure",
                    models.TextField(
                        choices=[
                            ("ERIE_IRON_LLC", "Erie iron llc"),
                            ("SEPARATE_LLC", "Separate llc"),
                        ]
                    ),
                ),
                ("entity_structure_justification", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesslegalanalysis",
            },
        ),
        migrations.CreateModel(
            name="ProductInitiative",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                ("expected_kpi_lift", models.JSONField(default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
                (
                    "linked_goals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="initiatives",
                        to="erieiron_common.businessgoal",
                    ),
                ),
                (
                    "linked_kpis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="initiatives",
                        to="erieiron_common.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_productinitiative",
            },
        ),
        migrations.CreateModel(
            name="ProductRequirement",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField()),
                ("acceptance_criteria", models.TextField()),
                ("testable", models.BooleanField(default=True)),
                (
                    "product_initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="erieiron_common.productinitiative",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_productrequirement",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(default="")),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_interacted_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.person",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_project",
            },
        ),
        migrations.CreateModel(
            name="ProjectInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField(null=True)),
                ("response", models.TextField(null=True)),
                ("feedback", models.BooleanField(null=True)),
                ("channel", models.TextField(default="erieiron_system")),
                ("context_maker", models.TextField(null=True)),
                (
                    "intent",
                    models.TextField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            (
                                "CONTINUE_PREVIOUS_CONVERSATION",
                                "Continue previous conversation",
                            ),
                            ("ERIE_GENERATED", "Erie generated"),
                        ],
                        default=erieiron_common.enums.PromptIntent["UNKNOWN"],
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "parsed_prompt",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                ("waiting", models.BooleanField(default=False, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.person",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.project",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_projectinteraction",
            },
        ),
        migrations.CreateModel(
            name="ProjectInteractionFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("value", models.TextField()),
                (
                    "project_interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.projectinteraction",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_projectinteractionfeature",
            },
        ),
        migrations.CreateModel(
            name="PubSubHanderInstance",
            fields=[
                (
                    "id",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
                ("env", models.TextField(db_index=True, default="production")),
                (
                    "instance_status",
                    models.TextField(
                        default=erieiron_common.enums.PubSubHandlerInstanceStatus[
                            "NOT_AVAILABLE"
                        ]
                    ),
                ),
                ("max_db_connections", models.IntegerField(default=0)),
                ("used_db_connections", models.IntegerField(default=0)),
                ("system_capacity", models.TextField(null=True)),
                ("system_capacity_explanation", models.TextField(null=True)),
                ("mem_percent", models.IntegerField(default=0)),
                ("cpu_percent", models.IntegerField(default=0)),
                ("gpu_percent", models.IntegerField(default=0, null=True)),
                (
                    "compute_device",
                    models.TextField(
                        choices=[("cpu", "Cpu"), ("mps", "Mps"), ("cuda", "Cuda")],
                        null=True,
                    ),
                ),
                (
                    "first_heard_from",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("last_heard_from", models.DateTimeField(auto_now_add=True, null=True)),
                ("job_limits_def", models.TextField(null=True)),
                ("desired_process_count", models.IntegerField(default=0, null=True)),
                ("threads_per_process", models.IntegerField(default=3, null=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.pubsubenvironment",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_pubsubhanderinstance",
            },
        ),
        migrations.CreateModel(
            name="PubSubHanderInstanceProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pid", models.IntegerField()),
                (
                    "process_status",
                    models.TextField(
                        default=erieiron_common.enums.PubSubHandlerInstanceStatus[
                            "AVAILABLE"
                        ]
                    ),
                ),
                ("cmd", models.TextField(null=True)),
                (
                    "exclusive_priority",
                    models.TextField(
                        choices=[
                            ("HIGH", "High"),
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("first_heard_from", models.DateTimeField(auto_now_add=True)),
                ("last_heard_from", models.DateTimeField(auto_now_add=True)),
                (
                    "current_threads",
                    models.JSONField(
                        default=dict,
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                    ),
                ),
                (
                    "handler_instance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.pubsubhanderinstance",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_pubsubhanderinstanceprocess",
            },
        ),
        migrations.CreateModel(
            name="SelfDrivingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("config_path", models.TextField()),
                ("sandbox_root_dir", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_selfdrivingtask",
            },
        ),
        migrations.CreateModel(
            name="SelfDrivingTaskIteration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("achieved_goal", models.BooleanField(default=False)),
                ("version_number", models.IntegerField(default=0)),
                ("planning_model", models.TextField()),
                ("coding_model", models.TextField()),
                ("log_content", models.TextField()),
                ("evaluation_json", models.JSONField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtask",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_selfdrivingtaskiteration",
            },
        ),
        migrations.CreateModel(
            name="SelfDrivingTaskBestIteration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtask",
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_selfdrivingtaskbestiteration",
            },
        ),
        migrations.CreateModel(
            name="LlmRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_count", models.IntegerField()),
                ("price", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task_iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_llmrequest",
            },
        ),
        migrations.CreateModel(
            name="CodeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_instructions", models.JSONField(null=True)),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.codefile",
                    ),
                ),
                (
                    "task_iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_codeversion",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ]
                    ),
                ),
                ("task_description", models.TextField()),
                ("raw_llm_payload", models.JSONField(default=list)),
                ("risk_notes", models.TextField()),
                ("test_plan", models.TextField()),
                (
                    "role_assignee",
                    models.TextField(
                        choices=[
                            ("HUMAN", "Human"),
                            ("ENGINEERING", "Engineering"),
                            ("DESIGN", "Design"),
                        ]
                    ),
                ),
                ("completion_criteria", models.JSONField(default=list)),
                ("comment_requests", models.JSONField(default=list)),
                ("max_budget_usd", models.FloatField(null=True)),
                ("attachments", models.JSONField(default=list)),
                ("created_by", models.TextField(null=True)),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_tasks",
                        to="erieiron_common.task",
                    ),
                ),
                (
                    "product_initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_tasks",
                        to="erieiron_common.productinitiative",
                    ),
                ),
                (
                    "validated_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="validation_tasks",
                        to="erieiron_common.productrequirement",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_task",
            },
        ),
        migrations.AddField(
            model_name="selfdrivingtask",
            name="related_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erieiron_common.task",
            ),
        ),
        migrations.CreateModel(
            name="TaskDesignRequirements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layout", models.JSONField(default=dict, null=True)),
                (
                    "component_ids",
                    models.ManyToManyField(
                        blank=True, to="erieiron_common.designcomponent"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_handoff",
                        to="erieiron_common.task",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_taskdesignrequirements",
            },
        ),
    ]
