# Generated by Django 5.1.6 on 2025-05-30 04:46

import django.contrib.postgres.search
import django.db.models.deletion
import erieiron_common.enums
import erieiron_common.json_encoder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "business",
            },
        ),
        migrations.CreateModel(
            name="CacheData",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
                ("val", models.TextField()),
            ],
            options={
                "db_table": "cachedata",
            },
        ),
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(null=True)),
                ("endpoint", models.URLField(null=True)),
                ("estimated_cost_per_execution", models.FloatField(null=True)),
                ("version", models.TextField(null=True)),
                ("used_by_businesses", models.JSONField(default=list)),
            ],
            options={
                "db_table": "capability",
            },
        ),
        migrations.CreateModel(
            name="CodeFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cognito_sub",
                    models.UUIDField(db_index=True, null=True, unique=True),
                ),
                ("name", models.TextField(null=True)),
                ("email", models.TextField()),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("banned", "Banned"),
                            ("free_user", "Free user"),
                            ("subscriber", "Subscriber"),
                            ("subscriber_pro", "Subscriber pro"),
                            ("beta_user", "Beta user"),
                            ("admin", "Admin"),
                            ("developer", "Developer"),
                            ("system", "System"),
                        ],
                        default="free_user",
                    ),
                ),
                ("server_root", models.TextField(null=True)),
                ("last_updated", models.DateTimeField(null=True)),
                (
                    "cookie_consent",
                    models.CharField(
                        blank=True,
                        choices=[("accepted", "Accepted"), ("declined", "Declined")],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "analytics_cookie_consent",
                    models.CharField(
                        blank=True,
                        choices=[("accepted", "Accepted"), ("declined", "Declined")],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "person",
            },
        ),
        migrations.CreateModel(
            name="PubSubEnvironment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("desired_handler_instance_count", models.IntegerField(default=1)),
                (
                    "last_requested_increase",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
            options={
                "db_table": "pubsub_environment",
            },
        ),
        migrations.CreateModel(
            name="PubSubMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("env", models.TextField(db_index=True)),
                ("namespace", models.TextField(db_index=True)),
                ("message_type", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        default="normal",
                        null=True,
                    ),
                ),
                ("status", models.TextField()),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("handler_instance_id", models.TextField(db_index=True, null=True)),
                ("retry_count", models.IntegerField(default=1, null=True)),
                ("error_message", models.TextField(null=True)),
                ("message_batch_idx", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "pubsub_message",
            },
        ),
        migrations.CreateModel(
            name="RuntimeConfigVal",
            fields=[
                (
                    "name",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
                ("value", models.TextField(null=True)),
            ],
            options={
                "db_table": "runtime_config",
            },
        ),
        migrations.CreateModel(
            name="ShutdownTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("condition", models.TextField()),
                (
                    "severity",
                    models.TextField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")]
                    ),
                ),
            ],
            options={
                "db_table": "shutdown_trigger",
            },
        ),
        migrations.CreateModel(
            name="CapabilityExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "executor",
                    models.TextField(
                        choices=[("AUTONOMOUS", "Autonomous"), ("HUMAN", "Human")]
                    ),
                ),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("NEW", "New"),
                            ("PENDING", "Pending"),
                            ("RETRYING", "Retrying"),
                            ("BLOCKED", "Blocked"),
                            ("EXPIRED", "Expired"),
                            ("RESOLVED", "Resolved"),
                        ]
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAIL_RETRYABLE", "Fail Retryable"),
                            ("FAIL_FATAL", "Fail Fatal"),
                            ("TIMEOUT", "Timeout"),
                            ("BLOCKED_DEPENDENCY", "Blocked Dependency"),
                        ]
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("cost", models.FloatField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.capability",
                    ),
                ),
            ],
            options={
                "db_table": "capability_execution",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "type",
                    models.TextField(
                        choices=[("KPI", "Kpi"), ("MILESTONE", "Milestone")]
                    ),
                ),
                ("target_value", models.TextField()),
                ("actual_value", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("ON_TRACK", "On Track"),
                            ("AT_RISK", "At Risk"),
                            ("OFF_TRACK", "Off Track"),
                        ]
                    ),
                ),
                ("evaluation_interval_days", models.IntegerField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "goal",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(default="")),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_interacted_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.person",
                    ),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="ProjectInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField(null=True)),
                ("response", models.TextField(null=True)),
                ("feedback", models.BooleanField(null=True)),
                ("channel", models.TextField(default="erieiron_system")),
                ("context_maker", models.TextField(null=True)),
                (
                    "intent",
                    models.TextField(
                        choices=[
                            ("unknown", "Unknown"),
                            (
                                "continue_previous_conversation",
                                "Continue previous conversation",
                            ),
                            ("erie_generated", "Erie generated"),
                        ],
                        default=erieiron_common.enums.PromptIntent["UNKNOWN"],
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "parsed_prompt",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                ("waiting", models.BooleanField(default=False, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.person",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_interaction",
            },
        ),
        migrations.CreateModel(
            name="ProjectInteractionFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("value", models.TextField()),
                (
                    "project_interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.projectinteraction",
                    ),
                ),
            ],
            options={
                "db_table": "project_interaction_feature",
            },
        ),
        migrations.CreateModel(
            name="PubSubHanderInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("env", models.TextField(db_index=True, default="production")),
                (
                    "instance_status",
                    models.TextField(
                        default=erieiron_common.enums.PubSubHandlerInstanceStatus[
                            "NOT_AVAILABLE"
                        ]
                    ),
                ),
                ("max_db_connections", models.IntegerField(default=0)),
                ("used_db_connections", models.IntegerField(default=0)),
                ("system_capacity", models.TextField(null=True)),
                ("system_capacity_explanation", models.TextField(null=True)),
                ("mem_percent", models.IntegerField(default=0)),
                ("cpu_percent", models.IntegerField(default=0)),
                ("gpu_percent", models.IntegerField(default=0, null=True)),
                (
                    "compute_device",
                    models.TextField(
                        choices=[("cpu", "Cpu"), ("mps", "Mps"), ("cuda", "Cuda")],
                        null=True,
                    ),
                ),
                (
                    "first_heard_from",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("last_heard_from", models.DateTimeField(auto_now_add=True, null=True)),
                ("job_limits_def", models.TextField(null=True)),
                ("desired_process_count", models.IntegerField(default=0, null=True)),
                ("threads_per_process", models.IntegerField(default=3, null=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.pubsubenvironment",
                    ),
                ),
            ],
            options={
                "db_table": "pubsub_message_handler_instance",
            },
        ),
        migrations.CreateModel(
            name="SelfDrivingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("config_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SelfDrivingTaskIteration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("planning_model", models.TextField()),
                ("coding_model", models.TextField()),
                ("log_content", models.TextField()),
                ("evaluation_json", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtask",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LlmRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_count", models.IntegerField()),
                ("price", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task_iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CodeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_instructions", models.JSONField()),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.codefile",
                    ),
                ),
                (
                    "task_iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShutdownPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("legal_review_completed", models.BooleanField(default=False)),
                ("ethical_review_completed", models.BooleanField(default=False)),
                ("data_purge_strategy", models.TextField(null=True)),
                ("user_communication_plan", models.TextField(null=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shutdown_plan",
                        to="erieiron_common.business",
                    ),
                ),
                (
                    "triggers",
                    models.ManyToManyField(
                        related_name="plans", to="erieiron_common.shutdowntrigger"
                    ),
                ),
            ],
            options={
                "db_table": "shutdown_plan",
            },
        ),
        migrations.CreateModel(
            name="PubSubHanderInstanceProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pid", models.IntegerField()),
                (
                    "process_status",
                    models.TextField(
                        default=erieiron_common.enums.PubSubHandlerInstanceStatus[
                            "AVAILABLE"
                        ]
                    ),
                ),
                ("cmd", models.TextField(null=True)),
                (
                    "exclusive_priority",
                    models.TextField(
                        choices=[
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("first_heard_from", models.DateTimeField(auto_now_add=True)),
                ("last_heard_from", models.DateTimeField(auto_now_add=True)),
                (
                    "current_threads",
                    models.JSONField(
                        default=dict,
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                    ),
                ),
                (
                    "handler_instance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erieiron_common.pubsubhanderinstance",
                    ),
                ),
            ],
            options={
                "db_table": "pubsub_message_handler_instance_process",
                "unique_together": {("handler_instance", "pid")},
            },
        ),
    ]
