# Generated by Django 5.1.6 on 2025-05-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeversion",
            name="code_instructions",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="selfdrivingtaskiteration",
            name="evaluation_json",
            field=models.JSONField(null=True),
        ),
    ]
