# Generated by Django 5.1.6 on 2025-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="raw_idea",
            field=models.TextField(null=True),
        ),
    ]
