# Generated by Django 5.1.6 on 2025-07-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cachedata",
            table="erieiron_cachedata",
        ),
        migrations.AlterModelTable(
            name="runtimeconfigval",
            table="erieiron_runtimeconfigval",
        ),
    ]
