# Generated by Django 5.1.6 on 2025-06-11 00:23

import django.db.models.deletion
import erieiron_common.json_encoder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0002_business_raw_idea"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessLegalAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField()),
                ("justification", models.TextField(null=True)),
                (
                    "required_disclaimers_or_terms",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                ("risk_rating", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_analyses",
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesslegalanalysis",
            },
        ),
    ]
