# Generated by Django 5.1.6 on 2025-11-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0002_alter_cachedata_table_alter_runtimeconfigval_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pubsubhanderinstance",
            name="env",
            field=models.TextField(db_index=True, default="dev"),
        ),
    ]
