# Generated by Django 5.1.6 on 2025-06-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="current_spend",
            field=models.FloatField(null=True),
        ),
    ]
