# Generated by Django 5.1.6 on 2025-06-01 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0002_alter_codeversion_code_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="version_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="codefile",
            name="file_path",
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name="SelfDrivingTaskBestIteration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtaskiteration",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.selfdrivingtask",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
