# Generated by Django 5.1.6 on 2025-11-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0003_alter_pubsubhanderinstance_env"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="personalization_info",
            field=models.TextField(
                blank=True,
                help_text="User's personalization preferences and notes",
                null=True,
            ),
        ),
    ]
