# Generated by Django 5.1.6 on 2025-06-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0003_selfdrivingtaskiteration_version_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="sandbox_root_dir",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
