# Generated by Django 5.1.6 on 2025-06-22 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0003_task_current_spend"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 22, 14, 32, 17, 718956, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
