# Generated by Django 5.1.6 on 2025-06-11 04:38

import django.db.models.deletion
import erieiron_common.enums
import erieiron_common.json_encoder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0003_businesslegalanalysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="macrotrend",
            name="business_analysis",
        ),
        migrations.RemoveField(
            model_name="monthlyexpense",
            name="business_analysis",
        ),
        migrations.RemoveField(
            model_name="portfoliorunlog",
            name="launched_business",
        ),
        migrations.RemoveField(
            model_name="potentialcompetitor",
            name="business_analysis",
        ),
        migrations.RemoveField(
            model_name="risk",
            name="business_analysis",
        ),
        migrations.RemoveField(
            model_name="shutdownplan",
            name="business",
        ),
        migrations.RemoveField(
            model_name="shutdownplan",
            name="triggers",
        ),
        migrations.RemoveField(
            model_name="shutdowntrigger",
            name="business",
        ),
        migrations.RemoveField(
            model_name="useoffunds",
            name="business_analysis",
        ),
        migrations.RemoveField(
            model_name="business",
            name="shutdown_rationale",
        ),
        migrations.AddField(
            model_name="businessanalysis",
            name="macro_trends_data",
            field=models.JSONField(
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="businessanalysis",
            name="monthly_expenses_data",
            field=models.JSONField(
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="businessanalysis",
            name="potential_competitors_data",
            field=models.JSONField(
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="businessanalysis",
            name="risks_data",
            field=models.JSONField(
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="businessanalysis",
            name="use_of_funds_data",
            field=models.JSONField(
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="autonomy_level",
            field=models.TextField(
                choices=[("100", "100"), ("050", "050"), ("000", "000")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="source",
            field=models.TextField(
                choices=[
                    ("HUMAN", "Human"),
                    ("BUSINESS_FINDER_AGENT", "Business finder agent"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="status",
            field=models.TextField(
                choices=[
                    ("IDEA", "Idea"),
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("SHUTDOWN", "Shutdown"),
                ],
                default=erieiron_common.enums.BusinessStatus["IDEA"],
            ),
        ),
        migrations.AlterField(
            model_name="businessanalysis",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="erieiron_common.business",
            ),
        ),
        migrations.AlterField(
            model_name="businesslegalanalysis",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="erieiron_common.business",
            ),
        ),
        migrations.AlterField(
            model_name="businesslegalanalysis",
            name="risk_rating",
            field=models.TextField(
                choices=[("100", "100"), ("050", "050"), ("000", "000")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="businessstructure",
            name="business",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="erieiron_common.business",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="erieiron_common.business",
            ),
        ),
        migrations.CreateModel(
            name="BusinessCapacityAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "compute_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "human_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                ("justification", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesscapacityanalysis",
            },
        ),
        migrations.CreateModel(
            name="BusinessGuidance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "guidance",
                    models.TextField(
                        choices=[
                            ("MAINTAIN", "Maintain"),
                            ("INCREASE_BUDGET", "Increase budget"),
                            ("DECREASE_BUDGET", "Decrease budget"),
                            ("SHUTDOWN", "Shutdown"),
                        ]
                    ),
                ),
                ("justification", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessguidance",
            },
        ),
        migrations.DeleteModel(
            name="BusinessReviewLog",
        ),
        migrations.DeleteModel(
            name="MacroTrend",
        ),
        migrations.DeleteModel(
            name="MonthlyExpense",
        ),
        migrations.DeleteModel(
            name="PortfolioRunLog",
        ),
        migrations.DeleteModel(
            name="PotentialCompetitor",
        ),
        migrations.DeleteModel(
            name="Risk",
        ),
        migrations.DeleteModel(
            name="ShutdownPlan",
        ),
        migrations.DeleteModel(
            name="ShutdownTrigger",
        ),
        migrations.DeleteModel(
            name="UseOfFunds",
        ),
    ]
