# Generated by Django 5.1.6 on 2025-06-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0004_selfdrivingtask_sandbox_root_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="achieved_goal",
            field=models.BooleanField(default=False),
        ),
    ]
