# Generated by Django 5.1.6 on 2025-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0004_remove_macrotrend_business_analysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="audience",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="business_plan",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="core_functions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="business",
            name="execution_dependencies",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="business",
            name="growth_channels",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="business",
            name="personalization_options",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="business",
            name="revenue_model",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="summary",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="value_prop",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="BusinessStructure",
        ),
    ]
