# Generated by Django 5.1.6 on 2025-06-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0004_task_created_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfdrivingtask",
            name="sandbox_root_dir",
        ),
    ]
