# Generated by Django 5.1.6 on 2025-11-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0004_person_personalization_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pubsubhanderinstance",
            name="last_heard_from",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="pubsubhanderinstanceprocess",
            name="last_heard_from",
            field=models.DateTimeField(),
        ),
    ]
