# Generated by Django 5.1.6 on 2025-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0005_remove_selfdrivingtask_sandbox_root_dir"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_description",
            new_name="description",
        ),
        migrations.AddField(
            model_name="task",
            name="phase",
            field=models.TextField(
                choices=[("EXECUTE", "Execute"), ("BUILD", "Build")], default="BUILD"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("RUN", "Run"),
                    ("MONITOR", "Monitor"),
                    ("VALIDATE", "Validate"),
                    ("DEPLOY", "Deploy"),
                ],
                null=True,
            ),
        ),
    ]
