# Generated by Django 5.1.6 on 2025-11-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0005_alter_pubsubhanderinstance_last_heard_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pubsubhanderinstanceprocess",
            name="last_heard_from",
        ),
    ]
