# Generated by Django 5.1.6 on 2025-06-11 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0005_business_audience_business_business_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="bank_account_id",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="BusinessBankBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("available_balance", models.FloatField(null=True)),
                ("current_balance", models.FloatField(null=True)),
                ("status", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessbankbalancesnapshot",
            },
        ),
    ]
