# Generated by Django 5.1.6 on 2025-06-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_common",
            "0006_rename_task_description_task_description_task_phase_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="goal",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="selfdrivingtask",
            name="config_path",
            field=models.TextField(null=True),
        ),
    ]
