# Generated by Django 5.1.6 on 2025-11-18 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0006_remove_pubsubhanderinstanceprocess_last_heard_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubsubhanderinstanceprocess",
            name="last_heard_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
