# Generated by Django 5.1.6 on 2025-06-11 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_common",
            "0006_business_bank_account_id_businessbankbalancesnapshot",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessbankbalancesnapshot",
            name="available_balance",
        ),
        migrations.RemoveField(
            model_name="businessbankbalancesnapshot",
            name="current_balance",
        ),
        migrations.RemoveField(
            model_name="businessbankbalancesnapshot",
            name="status",
        ),
        migrations.CreateModel(
            name="BusinessBankBalanceSnapshotAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_name", models.TextField()),
                ("account_id", models.TextField()),
                ("available_balance", models.FloatField(null=True)),
                ("current_balance", models.FloatField(null=True)),
                ("status", models.TextField(null=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.businessbankbalancesnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessbankbalancesnapshotaccount",
            },
        ),
    ]
