# Generated by Django 5.1.6 on 2025-11-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0007_pubsubhanderinstanceprocess_last_heard_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pubsubhanderinstanceprocess",
            name="last_heard_from",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
