# Generated by Django 5.1.6 on 2025-06-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0007_selfdrivingtask_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="main_name",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
    ]
