# Generated by Django 5.1.6 on 2025-06-12 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_common",
            "0007_remove_businessbankbalancesnapshot_available_balance_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCeoDirective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("target_agent", models.TextField()),
                ("directive_summary", models.TextField()),
                ("goal_alignment", models.JSONField(default=list)),
                ("kpi_targets", models.JSONField(default=dict)),
                ("initiative_reference", models.TextField(default="")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessceodirective",
            },
        ),
        migrations.CreateModel(
            name="BusinessKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("kpi_id", models.TextField()),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
                ("target_value", models.FloatField()),
                ("unit", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesskpi",
            },
        ),
        migrations.CreateModel(
            name="BusinessGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("goal_id", models.TextField()),
                ("description", models.TextField()),
                ("target_value", models.FloatField()),
                ("unit", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("ON_TRACK", "On track"),
                            ("AT_RISK", "At risk"),
                            ("OFF_TRACK", "Off track"),
                        ]
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessgoal",
            },
        ),
        migrations.CreateModel(
            name="BusinessKPIProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesskpiprogress",
            },
        ),
        migrations.DeleteModel(
            name="Goal",
        ),
    ]
