# Generated by Django 5.1.6 on 2025-06-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_common",
            "0008_businessceodirective_businesskpi_businessgoal_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInitiative",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                ("linked_kpis", models.JSONField(default=list)),
                ("linked_goals", models.JSONField(default=list)),
                ("expected_kpi_lift", models.JSONField(default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductRequirement",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField()),
                ("acceptance_criteria", models.TextField()),
                ("testable", models.BooleanField(default=True)),
                (
                    "product_initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="erieiron_common.productinitiative",
                    ),
                ),
            ],
        ),
    ]
