# Generated by Django 5.1.6 on 2025-06-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0008_selfdrivingtask_main_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfdrivingtask",
            name="config_path",
            field=models.TextField(db_index=True, null=True),
        ),
    ]
