# Generated by Django 5.1.6 on 2026-01-03 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0008_alter_pubsubhanderinstanceprocess_last_heard_from"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="django_user",
            field=models.OneToOneField(
                blank=True,
                help_text="Django User for authentication (linked via OAuthAccount)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
