# Generated by Django 5.1.6 on 2025-06-24 04:44

import django.db.models.deletion
import erieiron_common.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0009_alter_selfdrivingtask_config_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="db_name",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("BLOCKED", "Blocked"),
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default=erieiron_common.enums.TaskStatus["NOT_STARTED"],
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("executed_time", models.DateTimeField(null=True)),
                ("input", models.JSONField(default=dict, null=True)),
                ("output", models.JSONField(default=dict, null=True)),
                ("error_msg", models.TextField(null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.task",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_taskexecution",
            },
        ),
    ]
