# Generated by Django 5.1.6 on 2025-06-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0009_productinitiative_productrequirement"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productinitiative",
            table="erieiron_productinitiative",
        ),
        migrations.AlterModelTable(
            name="productrequirement",
            table="erieiron_productrequirement",
        ),
    ]
