# Generated by Django 5.1.6 on 2026-01-04 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0115_oauthaccount"),
        ("erieiron_common", "0009_person_django_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonBusinessAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_associations",
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_associations",
                        to="erieiron_common.person",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_personbusinessassociation",
                "indexes": [
                    models.Index(
                        fields=["person"], name="erieiron_pe_person__96400c_idx"
                    ),
                    models.Index(
                        fields=["business"], name="erieiron_pe_busines_dfd624_idx"
                    ),
                ],
                "unique_together": {("person", "business")},
            },
        ),
    ]
