# Generated by Django 5.1.6 on 2025-06-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0010_business_db_name_taskexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="aws_tag",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
    ]
