# Generated by Django 5.1.6 on 2025-06-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0010_alter_productinitiative_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capabilityexecution",
            name="capability",
        ),
        migrations.RemoveField(
            model_name="capabilityexecution",
            name="business",
        ),
        migrations.DeleteModel(
            name="Capability",
        ),
        migrations.DeleteModel(
            name="CapabilityExecution",
        ),
    ]
