# Generated by Django 5.1.6 on 2025-06-24 16:12

import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0011_business_aws_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="execution_mode",
            field=models.TextField(
                choices=[("HOST", "Host"), ("CONTAINER", "Container")],
                default=erieiron_common.enums.TaskExecutionMode["CONTAINER"],
            ),
        ),
    ]
