# Generated by Django 5.1.6 on 2025-06-13 03:27

import django.db.models.deletion
import erieiron_common.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0011_remove_capabilityexecution_capability_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(null=True)),
                ("inputs", models.JSONField(default=dict)),
                ("output_schema", models.JSONField(default=dict)),
                ("test_plan", models.TextField(null=True)),
                ("runtime_env", models.TextField(null=True)),
                ("entry_point", models.TextField(null=True)),
                ("execution_sandbox", models.TextField(null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SPECIFIED", "Specified"),
                            ("BUILDING", "Building"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default=erieiron_common.enums.CapabilityStatus["PENDING"],
                    ),
                ),
                ("can_be_built_autonomously", models.BooleanField(default=True)),
                ("builder_notes", models.TextField(null=True)),
                ("last_built_at", models.DateTimeField(null=True)),
                (
                    "implemented_by",
                    models.TextField(
                        help_text="Name of the person or LLM models used to implement this capability",
                        null=True,
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(blank=True, to="erieiron_common.capability"),
                ),
            ],
            options={
                "db_table": "erieiron_capability",
            },
        ),
        migrations.CreateModel(
            name="EngineeringTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.TextField()),
                ("task_description", models.TextField()),
                ("depends_on", models.JSONField(default=list)),
                ("raw_llm_payload", models.JSONField(default=list)),
                ("risk_notes", models.TextField()),
                ("test_plan", models.TextField()),
                (
                    "execution_mode",
                    models.TextField(
                        choices=[("HUMAN", "Human"), ("AUTONOMOUS", "Autonomous")]
                    ),
                ),
                (
                    "product_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.productrequirement",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_engineeringtask",
            },
        ),
        migrations.CreateModel(
            name="EngineeringTaskStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_index", models.IntegerField()),
                ("inputs", models.JSONField(default=dict)),
                ("outputs", models.JSONField(default=dict)),
                (
                    "capabilities",
                    models.ManyToManyField(blank=True, to="erieiron_common.capability"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.engineeringtask",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_engineeringtaskstep",
            },
        ),
    ]
