# Generated by Django 5.1.6 on 2025-06-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0012_task_execution_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="requires_test",
            field=models.BooleanField(default=True),
        ),
    ]
