# Generated by Django 5.1.6 on 2025-06-13 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0012_capability_engineeringtask_engineeringtaskstep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engineeringtask",
            name="product_requirement",
        ),
        migrations.AddField(
            model_name="engineeringtask",
            name="product_initiative",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engineering_tasks",
                to="erieiron_common.productinitiative",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="engineeringtask",
            name="validated_requirements",
            field=models.ManyToManyField(
                blank=True,
                related_name="validation_tasks",
                to="erieiron_common.productrequirement",
            ),
        ),
        migrations.RemoveField(
            model_name="productinitiative",
            name="linked_goals",
        ),
        migrations.RemoveField(
            model_name="productinitiative",
            name="linked_kpis",
        ),
        migrations.AddField(
            model_name="productinitiative",
            name="linked_goals",
            field=models.ManyToManyField(
                blank=True,
                related_name="initiatives",
                to="erieiron_common.businessgoal",
            ),
        ),
        migrations.AddField(
            model_name="productinitiative",
            name="linked_kpis",
            field=models.ManyToManyField(
                blank=True, related_name="initiatives", to="erieiron_common.businesskpi"
            ),
        ),
    ]
