# Generated by Django 5.1.6 on 2025-06-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0013_remove_engineeringtask_product_requirement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineeringtask",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
