# Generated by Django 5.1.6 on 2025-06-24 17:27

import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0013_task_requires_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="execution_schedule",
            field=models.TextField(
                choices=[
                    ("ONCE", "Once"),
                    ("DAEMON", "Daemon"),
                    ("HOURLY", "Hourly"),
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                ],
                default=erieiron_common.enums.TaskExecutionSchedule["ONCE"],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="execution_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
