# Generated by Django 5.1.6 on 2025-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0014_task_execution_schedule_task_execution_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="iam_role_name",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
    ]
