# Generated by Django 5.1.6 on 2025-06-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0014_alter_engineeringtask_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capability",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
