# Generated by Django 5.1.6 on 2025-06-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0015_business_iam_role_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="raw_llm_payload",
        ),
    ]
