# Generated by Django 5.1.6 on 2025-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0016_remove_engineeringtask_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engineeringtaskstep",
            name="capabilities",
        ),
        migrations.RemoveField(
            model_name="engineeringtaskstep",
            name="task",
        ),
        migrations.AddField(
            model_name="engineeringtask",
            name="attachments",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="engineeringtask",
            name="comment_requests",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="engineeringtask",
            name="completion_criteria",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="engineeringtask",
            name="max_budget_usd",
            field=models.FloatField(null=True),
        ),
        migrations.RemoveField(
            model_name="engineeringtask",
            name="depends_on",
        ),
        migrations.DeleteModel(
            name="Capability",
        ),
        migrations.DeleteModel(
            name="EngineeringTaskStep",
        ),
        migrations.AddField(
            model_name="engineeringtask",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_tasks",
                to="erieiron_common.engineeringtask",
            ),
        ),
    ]
