# Generated by Django 5.1.6 on 2025-06-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0017_business_repo_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="service_token",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
    ]
