# Generated by Django 5.1.6 on 2025-06-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0018_business_service_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="aws_tag",
        ),
        migrations.RemoveField(
            model_name="business",
            name="db_name",
        ),
        migrations.RemoveField(
            model_name="business",
            name="iam_role_name",
        ),
        migrations.RemoveField(
            model_name="business",
            name="repo_prefix",
        ),
    ]
