# Generated by Django 5.1.6 on 2025-06-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0018_selfdrivingtask_engineering_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfdrivingtask",
            name="engineering_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erieiron_common.engineeringtask",
            ),
        ),
    ]
