# Generated by Django 5.1.6 on 2025-06-13 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0019_alter_selfdrivingtask_engineering_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignComponent",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "erieiron_designcomponent",
            },
        ),
        migrations.CreateModel(
            name="DesignToken",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("value", models.TextField()),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "erieiron_designtoken",
            },
        ),
        migrations.CreateModel(
            name="EngineeringTaskDesignHandoff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layout", models.JSONField(default=dict, null=True)),
                (
                    "component_ids",
                    models.ManyToManyField(
                        blank=True, to="erieiron_common.designcomponent"
                    ),
                ),
                (
                    "design_tokens",
                    models.ManyToManyField(
                        blank=True, to="erieiron_common.designtoken"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_handoff",
                        to="erieiron_common.engineeringtask",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_engineeringtaskdesignhandoff",
            },
        ),
    ]
