# Generated by Django 5.1.6 on 2025-06-29 20:20

import django.db.models.deletion
import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_common",
            "0019_remove_business_aws_tag_remove_business_db_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrequirement",
            name="product_initiative",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="product_initiative",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "initiative_type",
                    models.TextField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("ENGINEERING", "Engineering"),
                            ("SALES", "Sales"),
                        ],
                        default=erieiron_common.enums.InitiativeType["PRODUCT"],
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                ("expected_kpi_lift", models.JSONField(default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_common.business",
                    ),
                ),
                (
                    "linked_goals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="initiatives",
                        to="erieiron_common.businessgoal",
                    ),
                ),
                (
                    "linked_kpis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="initiatives",
                        to="erieiron_common.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_initiative",
            },
        ),
        migrations.AddField(
            model_name="productrequirement",
            name="initiative",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="erieiron_common.initiative",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="initiative",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engineering_tasks",
                to="erieiron_common.initiative",
            ),
        ),
        migrations.DeleteModel(
            name="ProductInitiative",
        ),
    ]
