# Generated by Django 5.1.6 on 2025-06-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0020_designcomponent_designtoken_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engineeringtask",
            name="execution_mode",
        ),
        migrations.AddField(
            model_name="engineeringtask",
            name="role_assignee",
            field=models.TextField(
                choices=[
                    ("HUMAN", "Human"),
                    ("ENGINEERING", "Engineering"),
                    ("DESIGN", "Design"),
                ],
                default="",
            ),
            preserve_default=False,
        ),
    ]
