# Generated by Django 5.1.6 on 2025-06-29 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_common",
            "0020_alter_productrequirement_product_initiative_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrequirement",
            name="initiative",
            field=models.ForeignKey(
                default="asdf",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="erieiron_common.initiative",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productrequirement",
            name="product_initiative",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="initiative",
            field=models.ForeignKey(
                default="asdf",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="erieiron_common.initiative",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="product_initiative",
            field=models.TextField(null=True),
        ),
    ]
