# Generated by Django 5.1.6 on 2025-06-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0021_remove_engineeringtask_execution_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineeringtask",
            name="status",
            field=models.TextField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_STARTED",
            ),
            preserve_default=False,
        ),
    ]
