# Generated by Django 5.1.6 on 2025-06-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0021_alter_productrequirement_initiative_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="service_token",
            field=models.TextField(null=True),
        ),
    ]
