# Generated by Django 5.1.6 on 2025-07-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0022_alter_business_service_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="requires_unit_tests",
            field=models.BooleanField(default=True),
        ),
    ]
