# Generated by Django 5.1.6 on 2025-06-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0022_engineeringtask_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engineeringtaskdesignhandoff",
            name="design_tokens",
        ),
        migrations.DeleteModel(
            name="DesignToken",
        ),
    ]
