# Generated by Django 5.1.6 on 2025-06-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_common",
            "0023_remove_engineeringtaskdesignhandoff_design_tokens_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="sandbox_dir_name",
            field=models.TextField(null=True),
        ),
    ]
