# Generated by Django 5.1.6 on 2025-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0023_initiative_requires_unit_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdesignrequirements",
            name="component_tree",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="taskdesignrequirements",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
