# Generated by Django 5.1.6 on 2025-06-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0024_business_sandbox_dir_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="sandbox_dir_name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
