# Generated by Django 5.1.6 on 2025-07-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0024_taskdesignrequirements_component_tree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="guidance",
            field=models.TextField(blank=True, null=True),
        ),
    ]
