# Generated by Django 5.1.6 on 2025-07-02 01:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0025_task_guidance"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunningProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("process_id", models.IntegerField(blank=True, null=True)),
                ("container_id", models.TextField(blank=True, null=True)),
                (
                    "execution_type",
                    models.TextField(
                        choices=[("local", "Local"), ("docker", "Docker")],
                        max_length=20,
                    ),
                ),
                ("log_file_path", models.TextField(blank=True, null=True)),
                ("log_tail", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("is_running", models.BooleanField(default=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task_execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_process",
                        to="erieiron_common.taskexecution",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_runningprocess",
            },
        ),
    ]
