# Generated by Django 5.1.6 on 2025-06-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0025_alter_business_sandbox_dir_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesslegalanalysis",
            name="entity_structure_justification",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="businesslegalanalysis",
            name="recommended_entity_structure",
            field=models.TextField(
                choices=[
                    ("ERIE_IRON_LLC", "Erie iron llc"),
                    ("SEPARATE_LLC", "Separate llc"),
                ],
                default="ERIE_IRON_LLC",
            ),
            preserve_default=False,
        ),
    ]
