# Generated by Django 5.1.6 on 2025-07-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0027_alter_runningprocess_task_execution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runningprocess",
            name="task_execution",
        ),
        migrations.AddField(
            model_name="runningprocess",
            name="self_driving_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self_driving_task",
                to="erieiron_common.selfdrivingtask",
            ),
        ),
    ]
