# Generated by Django 5.1.6 on 2025-07-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0029_remove_runningprocess_self_driving_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="source_message",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erieiron_common.pubsubmessage",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="timeout_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
