# Generated by Django 5.1.6 on 2025-07-02 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0030_task_source_message_task_timeout_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="source_message",
        ),
    ]
