# Generated by Django 5.1.6 on 2025-07-03 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0031_remove_task_source_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecution",
            name="iteration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erieiron_common.selfdrivingtaskiteration",
            ),
        ),
    ]
