# Generated by Django 5.1.6 on 2025-07-03 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0032_taskexecution_iteration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runningprocess",
            name="iteration",
        ),
        migrations.AddField(
            model_name="runningprocess",
            name="task_execution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_execution",
                to="erieiron_common.taskexecution",
            ),
        ),
    ]
