# Generated by Django 5.1.6 on 2025-07-03 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0034_alter_runningprocess_task_execution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runningprocess",
            name="task_execution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process",
                to="erieiron_common.taskexecution",
            ),
        ),
    ]
