# Generated by Django 5.1.6 on 2025-07-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_common", "0035_alter_runningprocess_task_execution"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfdrivingtaskiteration",
            old_name="task",
            new_name="self_driving_task",
        ),
    ]
