# Generated by Django 5.1.6 on 2025-07-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_common",
            "0036_rename_task_selfdrivingtaskiteration_self_driving_task",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfdrivingtask",
            old_name="related_task",
            new_name="task",
        ),
    ]
