# Generated by Django 5.1.6 on 2025-07-04 16:20

import django.db.models.deletion
import erieiron_autonomous_agent.enums
import erieiron_common.json_encoder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "source",
                    models.TextField(
                        choices=[
                            ("HUMAN", "Human"),
                            ("BUSINESS_FINDER_AGENT", "Business finder agent"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("IDEA", "Idea"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("SHUTDOWN", "Shutdown"),
                        ],
                        default=erieiron_autonomous_agent.enums.BusinessStatus["IDEA"],
                    ),
                ),
                ("sandbox_dir_name", models.TextField()),
                ("service_token", models.TextField(null=True)),
                ("summary", models.TextField(null=True)),
                ("raw_idea", models.TextField(null=True)),
                ("bank_account_id", models.TextField(null=True)),
                ("business_plan", models.TextField(null=True)),
                ("value_prop", models.TextField(null=True)),
                ("revenue_model", models.TextField(null=True)),
                ("audience", models.TextField(null=True)),
                ("core_functions", models.JSONField(default=list)),
                ("execution_dependencies", models.JSONField(default=list)),
                ("growth_channels", models.JSONField(default=list)),
                ("personalization_options", models.JSONField(default=list)),
                ("allow_autonomous_shutdown", models.BooleanField(default=True)),
                (
                    "autonomy_level",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "erieiron_business",
            },
        ),
        migrations.CreateModel(
            name="CodeFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_path", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "erieiron_codefile",
            },
        ),
        migrations.CreateModel(
            name="DesignComponent",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "erieiron_designcomponent",
            },
        ),
        migrations.CreateModel(
            name="BusinessAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("business_name", models.TextField()),
                (
                    "estimated_monthly_revenue_at_steady_state_usd",
                    models.FloatField(null=True),
                ),
                ("time_to_profit_estimate_months", models.IntegerField(null=True)),
                ("potential_mode", models.TextField(null=True)),
                ("summary", models.TextField(null=True)),
                ("final_recommendation_justification", models.TextField(null=True)),
                ("final_recommendation_score_1_to_10", models.IntegerField(null=True)),
                (
                    "estimated_operating_total_cost_per_month_usd",
                    models.FloatField(null=True),
                ),
                (
                    "upfront_investment_estimated_amount_usd",
                    models.FloatField(null=True),
                ),
                (
                    "total_addressable_market_estimate_usd_per_year",
                    models.FloatField(null=True),
                ),
                (
                    "total_addressable_market_source_or_rationale",
                    models.TextField(null=True),
                ),
                (
                    "macro_trends_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "risks_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "monthly_expenses_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "potential_competitors_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "use_of_funds_data",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessanalysis",
            },
        ),
        migrations.CreateModel(
            name="BusinessBankBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessbankbalancesnapshot",
            },
        ),
        migrations.CreateModel(
            name="BusinessBankBalanceSnapshotAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_name", models.TextField()),
                ("account_id", models.TextField()),
                ("available_balance", models.FloatField(null=True)),
                ("current_balance", models.FloatField(null=True)),
                ("status", models.TextField(null=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.businessbankbalancesnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessbankbalancesnapshotaccount",
            },
        ),
        migrations.CreateModel(
            name="BusinessCapacityAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "compute_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "human_capacity_status",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ]
                    ),
                ),
                ("justification", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesscapacityanalysis",
            },
        ),
        migrations.CreateModel(
            name="BusinessCeoDirective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("target_agent", models.TextField()),
                ("directive_summary", models.TextField()),
                ("goal_alignment", models.JSONField(default=list)),
                ("kpi_targets", models.JSONField(default=dict)),
                ("initiative_reference", models.TextField(default="")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessceodirective",
            },
        ),
        migrations.CreateModel(
            name="BusinessGuidance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "guidance",
                    models.TextField(
                        choices=[
                            ("MAINTAIN", "Maintain"),
                            ("INCREASE_BUDGET", "Increase budget"),
                            ("DECREASE_BUDGET", "Decrease budget"),
                            ("SHUTDOWN", "Shutdown"),
                        ]
                    ),
                ),
                ("justification", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessguidance",
            },
        ),
        migrations.CreateModel(
            name="BusinessKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("kpi_id", models.TextField()),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
                ("target_value", models.FloatField()),
                ("unit", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesskpi",
            },
        ),
        migrations.CreateModel(
            name="BusinessGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("goal_id", models.TextField()),
                ("description", models.TextField()),
                ("target_value", models.FloatField()),
                ("unit", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("ON_TRACK", "On track"),
                            ("AT_RISK", "At risk"),
                            ("OFF_TRACK", "Off track"),
                        ]
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessgoal",
            },
        ),
        migrations.CreateModel(
            name="BusinessKPIProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesskpiprogress",
            },
        ),
        migrations.CreateModel(
            name="BusinessLegalAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField()),
                ("justification", models.TextField(null=True)),
                (
                    "required_disclaimers_or_terms",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "risk_rating",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")],
                        null=True,
                    ),
                ),
                (
                    "recommended_entity_structure",
                    models.TextField(
                        choices=[
                            ("ERIE_IRON_LLC", "Erie iron llc"),
                            ("SEPARATE_LLC", "Separate llc"),
                        ]
                    ),
                ),
                ("entity_structure_justification", models.TextField(null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesslegalanalysis",
            },
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "initiative_type",
                    models.TextField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("ENGINEERING", "Engineering"),
                            ("SALES", "Sales"),
                        ],
                        default=erieiron_common.enums.InitiativeType["PRODUCT"],
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "priority",
                    models.TextField(
                        choices=[("100", "100"), ("050", "050"), ("000", "000")]
                    ),
                ),
                ("expected_kpi_lift", models.JSONField(default=dict)),
                ("requires_unit_tests", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
                (
                    "linked_goals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="initiatives",
                        to="erieiron_autonomous_agent.businessgoal",
                    ),
                ),
                (
                    "linked_kpis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="initiatives",
                        to="erieiron_autonomous_agent.businesskpi",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_initiative",
            },
        ),
        migrations.CreateModel(
            name="ProductRequirement",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("product_initiative", models.TextField(null=True)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField()),
                ("acceptance_criteria", models.TextField()),
                ("testable", models.BooleanField(default=True)),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="erieiron_autonomous_agent.initiative",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_productrequirement",
            },
        ),
        migrations.CreateModel(
            name="SelfDrivingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("main_name", models.TextField()),
                ("goal", models.TextField()),
                ("config_path", models.TextField(db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_selfdrivingtask",
            },
        ),
        migrations.CreateModel(
            name="SelfDrivingTaskIteration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("achieved_goal", models.BooleanField(default=False)),
                ("version_number", models.IntegerField(default=0)),
                ("planning_model", models.TextField()),
                ("coding_model", models.TextField()),
                ("log_content", models.TextField()),
                ("evaluation_json", models.JSONField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "self_driving_task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.selfdrivingtask",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_selfdrivingtaskiteration",
            },
        ),
        migrations.CreateModel(
            name="SelfDrivingTaskBestIteration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.selfdrivingtask",
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_selfdrivingtaskbestiteration",
            },
        ),
        migrations.CreateModel(
            name="LlmRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_count", models.IntegerField()),
                ("price", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task_iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_llmrequest",
            },
        ),
        migrations.CreateModel(
            name="CodeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_instructions", models.JSONField(null=True)),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.codefile",
                    ),
                ),
                (
                    "task_iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_codeversion",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("product_initiative", models.TextField(null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("BLOCKED", "Blocked"),
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ]
                    ),
                ),
                ("description", models.TextField()),
                ("risk_notes", models.TextField()),
                ("test_plan", models.TextField()),
                (
                    "role_assignee",
                    models.TextField(
                        choices=[
                            ("HUMAN", "Human"),
                            ("ENGINEERING", "Engineering"),
                            ("DESIGN", "Design"),
                        ]
                    ),
                ),
                ("completion_criteria", models.JSONField(default=list)),
                ("comment_requests", models.JSONField(default=list)),
                ("current_spend", models.FloatField(null=True)),
                ("max_budget_usd", models.FloatField(null=True)),
                ("attachments", models.JSONField(default=list)),
                ("created_by", models.TextField(null=True)),
                (
                    "phase",
                    models.TextField(
                        choices=[("EXECUTE", "Execute"), ("BUILD", "Build")]
                    ),
                ),
                (
                    "task_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("RUN", "Run"),
                            ("MONITOR", "Monitor"),
                            ("VALIDATE", "Validate"),
                            ("DEPLOY", "Deploy"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "execution_mode",
                    models.TextField(
                        choices=[("HOST", "Host"), ("CONTAINER", "Container")],
                        default=erieiron_autonomous_agent.enums.TaskExecutionMode[
                            "CONTAINER"
                        ],
                    ),
                ),
                ("requires_test", models.BooleanField(default=True)),
                (
                    "execution_schedule",
                    models.TextField(
                        choices=[
                            ("ONCE", "Once"),
                            ("DAEMON", "Daemon"),
                            ("HOURLY", "Hourly"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                        ],
                        default=erieiron_common.enums.TaskExecutionSchedule["ONCE"],
                    ),
                ),
                ("execution_start_time", models.DateTimeField(blank=True, null=True)),
                ("timeout_seconds", models.IntegerField(blank=True, null=True)),
                ("guidance", models.TextField(blank=True, null=True)),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_tasks",
                        to="erieiron_autonomous_agent.task",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="erieiron_autonomous_agent.initiative",
                    ),
                ),
                (
                    "validated_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="validation_tasks",
                        to="erieiron_autonomous_agent.productrequirement",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_task",
            },
        ),
        migrations.AddField(
            model_name="selfdrivingtask",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erieiron_autonomous_agent.task",
            ),
        ),
        migrations.CreateModel(
            name="TaskDesignRequirements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layout", models.JSONField(default=dict, null=True)),
                ("component_tree", models.JSONField(default=dict, null=True)),
                ("notes", models.TextField(null=True)),
                (
                    "component_ids",
                    models.ManyToManyField(
                        blank=True, to="erieiron_autonomous_agent.designcomponent"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_handoff",
                        to="erieiron_autonomous_agent.task",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_taskdesignrequirements",
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("BLOCKED", "Blocked"),
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default=erieiron_autonomous_agent.enums.TaskStatus[
                            "NOT_STARTED"
                        ],
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("executed_time", models.DateTimeField(null=True)),
                ("input", models.JSONField(default=dict, null=True)),
                ("output", models.JSONField(default=dict, null=True)),
                ("error_msg", models.TextField(null=True)),
                (
                    "iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.selfdrivingtaskiteration",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.task",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_taskexecution",
            },
        ),
        migrations.CreateModel(
            name="RunningProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("process_id", models.IntegerField(blank=True, null=True)),
                ("container_id", models.TextField(blank=True, null=True)),
                (
                    "execution_type",
                    models.TextField(
                        choices=[("local", "Local"), ("docker", "Docker")],
                        max_length=20,
                    ),
                ),
                ("log_file_path", models.TextField(blank=True, null=True)),
                ("log_tail", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("is_running", models.BooleanField(default=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task_execution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process",
                        to="erieiron_autonomous_agent.taskexecution",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_runningprocess",
            },
        ),
    ]
