# Generated by Django 5.2.4 on 2025-07-05 03:17

import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="execution_mode",
        ),
        migrations.RemoveField(
            model_name="task",
            name="phase",
        ),
        migrations.RemoveField(
            model_name="task",
            name="role_assignee",
        ),
        migrations.AddField(
            model_name="task",
            name="input_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="output_fields",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="task",
            name="execution_schedule",
            field=models.TextField(
                choices=[
                    ("NOT_APPLICABLE", "Not applicable"),
                    ("ONCE", "Once"),
                    ("DAEMON", "Daemon"),
                    ("HOURLY", "Hourly"),
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                ],
                default=erieiron_common.enums.TaskExecutionSchedule["ONCE"],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.TextField(
                choices=[
                    ("CODING_APPLICATION", "Coding web application"),
                    ("CODING_NON_UI_TASK", "Coding non ui task"),
                    ("CODING_ML", "Coding ml"),
                    ("TASK_EXECUTION", "Task execution"),
                    ("DESIGN_WEB_APPLICATION", "Design web application"),
                    ("HUMAN_WORK", "Human work"),
                ],
                default=erieiron_common.enums.TaskType["CODING_NON_UI_TASK"],
            ),
        ),
    ]
