# Generated by Django 5.2.4 on 2025-07-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0002_remove_task_execution_mode_remove_task_phase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessceodirective",
            name="initiative_reference",
        ),
    ]
