# Generated by Django 5.2.4 on 2025-07-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0003_remove_businessceodirective_initiative_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="github_repo_url",
            field=models.TextField(null=True),
        ),
    ]
