# Generated by Django 5.2.4 on 2025-07-08 13:48

import django.db.models.deletion
import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0004_business_github_repo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="codefile",
            name="business",
            field=models.ForeignKey(
                default="039ba1f5-c24d-48b2-b498-be5846632737",
                on_delete=django.db.models.deletion.CASCADE,
                to="erieiron_autonomous_agent.business",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.TextField(
                choices=[
                    ("BOOTSRAP_CLONE_REPO", "Bootsrap clone repo"),
                    ("BOOTSRAP_DEPLOY_ENVS", "Bootsrap deploy envs"),
                    ("CODING_APPLICATION", "Coding web application"),
                    ("CODING_NON_UI_TASK", "Coding non ui task"),
                    ("CODING_ML", "Coding ml"),
                    ("TASK_EXECUTION", "Task execution"),
                    ("DESIGN_WEB_APPLICATION", "Design web application"),
                    ("HUMAN_WORK", "Human work"),
                ],
                default=erieiron_common.enums.TaskType["CODING_NON_UI_TASK"],
            ),
        ),
    ]
