# Generated by Django 5.2.4 on 2025-07-09 02:41

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0005_codefile_business_alter_task_task_type"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="codeversion",
            name="codebert_embedding",
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
