# Generated by Django 5.1.6 on 2025-07-10 22:41

import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0006_codeversion_codebert_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="sandbox_dir_name",
        ),
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="sandbox_path",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.TextField(
                choices=[
                    ("BOOTSRAP_CLONE_REPO", "Bootsrap clone repo"),
                    ("CODING_WEB_APPLICATION", "Coding web application"),
                    ("CODING_NON_UI_TASK", "Coding non ui task"),
                    ("CODING_ML", "Coding ml"),
                    ("TASK_EXECUTION", "Task execution"),
                    ("DESIGN_WEB_APPLICATION", "Design web application"),
                    ("HUMAN_WORK", "Human work"),
                ],
                default=erieiron_common.enums.TaskType["CODING_NON_UI_TASK"],
            ),
        ),
    ]
