# Generated by Django 5.1.6 on 2025-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0007_remove_business_sandbox_dir_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfdrivingtaskiteration",
            name="sandbox_path",
        ),
        migrations.AddField(
            model_name="selfdrivingtask",
            name="sandbox_path",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
    ]
