# Generated by Django 5.1.6 on 2025-07-15 18:47

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0008_remove_selfdrivingtaskiteration_sandbox_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeMethod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("parameters", models.JSONField(default={})),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("codebert_embedding", pgvector.django.vector.VectorField(dimensions=768, null=True)),
                (
                    "code_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erieiron_autonomous_agent.codeversion"
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_codemethod",
            },
        ),
    ]
