# Generated by Django 5.1.6 on 2025-07-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0009_codemethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codefile",
            name="file_path",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="codemethod",
            name="parameters",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name="codefile",
            unique_together={("business", "file_path")},
        ),
    ]
