# Generated by Django 5.1.6 on 2025-07-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0010_alter_codefile_file_path_alter_codemethod_parameters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="execute_module",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="test_module",
            field=models.TextField(null=True),
        ),
    ]
