# Generated by Django 5.1.6 on 2025-07-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0011_selfdrivingtaskiteration_execute_module_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfdrivingtaskiteration",
            name="execute_module",
        ),
        migrations.RemoveField(
            model_name="selfdrivingtaskiteration",
            name="test_module",
        ),
    ]
