# Generated by Django 5.1.6 on 2025-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0012_remove_selfdrivingtaskiteration_execute_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="execute_module",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="test_module",
            field=models.TextField(null=True),
        ),
    ]
