# Generated by Django 5.1.6 on 2025-07-24 01:18

import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0013_selfdrivingtaskiteration_execute_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="cloudformation_stack_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.TextField(
                choices=[
                    ("BOOTSRAP_CLONE_REPO", "Bootsrap clone repo"),
                    ("CODING_APPLICATION", "Coding application"),
                    ("CODING_ML", "Coding ml"),
                    ("TASK_EXECUTION", "Task execution"),
                    ("DESIGN_WEB_APPLICATION", "Design web application"),
                    ("HUMAN_WORK", "Human work"),
                ],
                default=erieiron_common.enums.TaskType["CODING_APPLICATION"],
            ),
        ),
    ]
