# Generated by Django 5.1.6 on 2025-07-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0014_selfdrivingtask_cloudformation_stack_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfdrivingtaskiteration",
            old_name="log_content",
            new_name="log_content_execution",
        ),
    ]
