# Generated by Django 5.1.6 on 2025-07-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0015_rename_log_content_selfdrivingtaskiteration_log_content_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="log_content_coding",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="selfdrivingtaskiteration",
            name="log_content_execution",
            field=models.TextField(null=True),
        ),
    ]
