# Generated by Django 5.1.6 on 2025-07-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0016_selfdrivingtaskiteration_log_content_coding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="test_file_path",
            field=models.TextField(null=True),
        ),
    ]
