# Generated by Django 5.1.6 on 2025-07-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0017_selfdrivingtask_test_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="design_doc",
            field=models.TextField(null=True),
        ),
    ]
