# Generated by Django 5.1.6 on 2025-07-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0018_selfdrivingtask_design_doc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfdrivingtask",
            old_name="design_doc",
            new_name="design_doc_path",
        ),
    ]
