# Generated by Django 5.1.6 on 2025-07-30 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0019_rename_design_doc_selfdrivingtask_design_doc_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLesson",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pattern", models.TextField()),
                ("trigger", models.TextField()),
                ("lesson", models.TextField()),
                ("context_tags", models.JSONField(default=list)),
                (
                    "source_iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erieiron_autonomous_agent.selfdrivingtaskiteration",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_agentlesson",
            },
        ),
    ]
