# Generated by Django 5.1.6 on 2025-07-30 17:08

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0020_agentlesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlesson",
            name="agent_step",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agentlesson",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
