# Generated by Django 5.1.6 on 2025-07-30 17:12

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0021_agentlesson_agent_step_agentlesson_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentlesson",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
