# Generated by Django 5.1.6 on 2025-07-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0022_alter_agentlesson_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlesson",
            name="invalid_lesson",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
