# Generated by Django 5.1.6 on 2025-07-30 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0023_agentlesson_invalid_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlesson",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
