# Generated by Django 5.1.6 on 2025-08-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0024_agentlesson_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="routing_json",
            field=models.JSONField(null=True),
        ),
    ]
