# Generated by Django 5.1.6 on 2025-08-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0025_selfdrivingtaskiteration_routing_json"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfdrivingtaskiteration",
            old_name="routing_json",
            new_name="route_to_json",
        ),
    ]
