# Generated by Django 5.1.6 on 2025-08-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0026_rename_routing_json_selfdrivingtaskiteration_development_path_json"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfdrivingtaskiteration",
            old_name="route_to_json",
            new_name="routing_json",
        ),
    ]
