# Generated by Django 5.1.6 on 2025-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0027_rename_development_path_json_selfdrivingtaskiteration_routing_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="docker_tag",
            field=models.TextField(null=True),
        ),
    ]
