# Generated by Django 5.1.6 on 2025-08-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0029_selfdrivingtaskiteration_log_content_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="log_content_init",
            field=models.TextField(null=True),
        ),
    ]
