# Generated by Django 5.1.6 on 2025-08-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0030_selfdrivingtaskiteration_log_content_init"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="planning_json",
            field=models.JSONField(null=True),
        ),
    ]
