# Generated by Django 5.1.6 on 2025-08-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0031_selfdrivingtaskiteration_planning_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="start_iteration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erieiron_autonomous_agent.selfdrivingtaskiteration",
            ),
        ),
    ]
