# Generated by Django 5.1.6 on 2025-08-12 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0032_selfdrivingtaskiteration_start_iteration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTombstone",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("data_json", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="erieiron_autonomous_agent.business"
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_agenttombstone",
            },
        ),
    ]
