# Generated by Django 5.1.6 on 2025-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0033_agenttombstone"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="slowest_cloudformation_resources",
            field=models.JSONField(null=True),
        ),
    ]
