# Generated by Django 5.1.6 on 2025-08-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0034_selfdrivingtaskiteration_slowest_cloudformation_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="messages",
            field=models.JSONField(null=True),
        ),
    ]
