# Generated by Django 5.1.6 on 2025-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0035_llmrequest_messages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmrequest",
            old_name="messages",
            new_name="input_messages",
        ),
        migrations.AddField(
            model_name="llmrequest",
            name="response",
            field=models.TextField(null=True),
        ),
    ]
