# Generated by Django 5.1.6 on 2025-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0036_rename_messages_llmrequest_input_messages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="title",
            field=models.TextField(default="Unknown", null=True),
        ),
    ]
