# Generated by Django 5.1.6 on 2025-08-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0037_llmrequest_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="llm_model",
            field=models.TextField(null=True),
        ),
    ]
