# Generated by Django 5.1.6 on 2025-08-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0038_llmrequest_llm_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="reasoning_effort",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="llmrequest",
            name="verbosity",
            field=models.TextField(null=True),
        ),
    ]
