# Generated by Django 5.1.6 on 2025-08-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0039_llmrequest_reasoning_effort_llmrequest_verbosity"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="resp_json",
            field=models.JSONField(null=True),
        ),
    ]
