# Generated by Django 5.1.6 on 2025-08-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0040_llmrequest_resp_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="required_credentials",
            field=models.JSONField(null=True),
        ),
    ]
