# Generated by Django 5.1.6 on 2025-08-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0041_business_required_credentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfdrivingtask",
            name="design_doc_path",
        ),
        migrations.AddField(
            model_name="business",
            name="architecture",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="architecture",
            field=models.TextField(null=True),
        ),
    ]
