# Generated by Django 5.1.6 on 2025-09-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0043_initiative_test_file_path_alter_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="sequence_idx",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
        ),
    ]
