# Generated by Django 5.1.6 on 2025-09-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0044_task_sequence_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sequence_idx",
            field=models.PositiveIntegerField(),
        ),
    ]
