# Generated by Django 5.1.6 on 2025-09-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0045_alter_task_sequence_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sequence_idx",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
