# Generated by Django 5.1.6 on 2025-09-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0046_alter_task_sequence_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="sequence_idx",
        ),
    ]
