# Generated by Django 5.1.6 on 2025-09-03 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0047_remove_task_sequence_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="business",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="erieiron_autonomous_agent.business"
            ),
        ),
        migrations.AddField(
            model_name="llmrequest",
            name="initiative",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="erieiron_autonomous_agent.initiative"
            ),
        ),
    ]
