# Generated by Django 5.1.6 on 2025-09-04 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0048_llmrequest_business_llmrequest_initiative"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="cloudformation_stack_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="llmrequest",
            name="business",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="erieiron_autonomous_agent.business"
            ),
        ),
        migrations.AlterField(
            model_name="llmrequest",
            name="initiative",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="erieiron_autonomous_agent.initiative"
            ),
        ),
        migrations.AlterField(
            model_name="llmrequest",
            name="task_iteration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erieiron_autonomous_agent.selfdrivingtaskiteration",
            ),
        ),
    ]
