# Generated by Django 5.1.6 on 2025-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0049_selfdrivingtask_cloudformation_stack_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="chat_millis",
            field=models.IntegerField(default=0),
        ),
    ]
