# Generated by Django 5.1.6 on 2025-09-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0050_llmrequest_chat_millis"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="needs_domain",
            field=models.BooleanField(default=False),
        ),
    ]
