# Generated by Django 5.1.6 on 2025-09-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0051_business_needs_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="domain",
            field=models.TextField(null=True),
        ),
    ]
