# Generated by Django 5.1.6 on 2025-10-03 00:26

import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0054_business_web_service_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.TextField(
                choices=[
                    ("BOOTSRAP_CLONE_REPO", "Bootsrap clone repo"),
                    ("PRODUCTION_DEPLOYMENT", "Production deployment"),
                    ("INITIATIVE_VERIFICATION", "Initiative verification"),
                    ("CODING_APPLICATION", "Coding application"),
                    ("CODING_ML", "Coding ml"),
                    ("TASK_EXECUTION", "Task execution"),
                    ("DESIGN_WEB_APPLICATION", "Design web application"),
                    ("HUMAN_WORK", "Human work"),
                ],
                default=erieiron_common.enums.TaskType["CODING_APPLICATION"],
            ),
        ),
    ]
