# Generated by Django 5.1.6 on 2025-10-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0055_alter_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="codex_command",
            field=models.TextField(null=True),
        ),
    ]
