# Generated by Django 5.1.6 on 2025-10-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0056_selfdrivingtaskiteration_codex_command"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfdrivingtaskiteration",
            name="codex_command",
        ),
    ]
