# Generated by Django 5.1.6 on 2025-10-09 04:58

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0057_remove_selfdrivingtaskiteration_codex_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttombstone",
            name="data_json",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder),
        ),
    ]
