# Generated by Django 5.1.6 on 2025-10-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0058_alter_agenttombstone_data_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="test_plan",
        ),
    ]
