# Generated by Django 5.1.6 on 2025-10-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0062_initiative_domain_stack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfdrivingtaskiteration",
            name="cloudformation_stack_id",
        ),
        migrations.RemoveField(
            model_name="selfdrivingtaskiteration",
            name="cloudformation_stack_name",
        ),
    ]
