# Generated by Django 5.1.6 on 2025-10-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0063_remove_selfdrivingtaskiteration_cloudformation_stack_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="cloudformation_stack_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="selfdrivingtask",
            name="cloudformation_stack_name",
            field=models.TextField(null=True),
        ),
    ]
