# Generated by Codex on 2025-02-15

import uuid

from django.db import migrations, models
import django.db.models.deletion

from erieiron_common.enums import InfrastructureStackType


def get_template_choices():
    return [(template.value, template.value) for template in InfrastructureStackType]


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0064_selfdrivingtask_cloudformation_stack_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfrastructureStack",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stack_id", models.TextField(blank=True, null=True)),
                ("stack_name", models.TextField(blank=True, null=True)),
                ("template_name", models.TextField(choices=get_template_choices())),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloudformation_stacks",
                        to="erieiron_autonomous_agent.initiative",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_infrastructurestack",
            },
        ),
        migrations.AddIndex(
            model_name="infrastructurestack",
            index=models.Index(fields=["business", "template_name"], name="infrastruct_busines_19a7d5_idx"),
        ),
        migrations.AddIndex(
            model_name="infrastructurestack",
            index=models.Index(fields=["initiative", "template_name"], name="infrastruct_initiat_30ae5a_idx"),
        ),
    ]
