# Generated by Codex on 2025-02-15

from django.db import migrations

from erieiron_common.enums import InfrastructureStackType


def create_cloudformation_stacks(apps, schema_editor):
    InfrastructureStack = apps.get_model("erieiron_autonomous_agent", "InfrastructureStack")
    Initiative = apps.get_model("erieiron_autonomous_agent", "Initiative")
    SelfDrivingTask = apps.get_model("erieiron_autonomous_agent", "SelfDrivingTask")

    foundation_template = InfrastructureStackType.FOUNDATION.value
    application_template = InfrastructureStackType.APPLICATION.value

    for initiative in Initiative.objects.exclude(cloudformation_stack_name__isnull=True).exclude(cloudformation_stack_name=""):
        if not initiative.cloudformation_stack_id:
            continue

        stack, created = InfrastructureStack.objects.get_or_create(
            business=initiative.business,
            initiative=initiative,
            template_name=foundation_template,
            defaults={
                "stack_id": initiative.cloudformation_stack_id,
                "stack_name": initiative.cloudformation_stack_name,
            },
        )

        if not created:
            updated = False
            if stack.stack_id != initiative.cloudformation_stack_id:
                stack.stack_id = initiative.cloudformation_stack_id
                updated = True
            if stack.stack_name != initiative.cloudformation_stack_name:
                stack.stack_name = initiative.cloudformation_stack_name
                updated = True
            if updated:
                stack.save(update_fields=["stack_id", "stack_name"])

    self_driving_tasks = SelfDrivingTask.objects.exclude(cloudformation_stack_name__isnull=True).exclude(cloudformation_stack_name="")
    for self_driving_task in self_driving_tasks:
        if not self_driving_task.cloudformation_stack_id:
            continue
        task = getattr(self_driving_task, "task", None)
        initiative = getattr(task, "initiative", None) if task else None
        if not initiative:
            continue

        stack, created = InfrastructureStack.objects.get_or_create(
            business=self_driving_task.business,
            initiative=initiative,
            template_name=application_template,
            defaults={
                "stack_id": self_driving_task.cloudformation_stack_id,
                "stack_name": self_driving_task.cloudformation_stack_name,
            },
        )

        if not created:
            updated = False
            if stack.stack_id != self_driving_task.cloudformation_stack_id:
                stack.stack_id = self_driving_task.cloudformation_stack_id
                updated = True
            if stack.stack_name != self_driving_task.cloudformation_stack_name:
                stack.stack_name = self_driving_task.cloudformation_stack_name
                updated = True
            if updated:
                stack.save(update_fields=["stack_id", "stack_name"])


def noop_reverse(apps, schema_editor):
    # This migration only backfills data from existing fields; nothing to undo safely.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0065_cloudformationstack"),
    ]

    operations = [
        migrations.RunPython(create_cloudformation_stacks, noop_reverse),
    ]
