# Generated by Django 5.1.6 on 2025-10-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0066_backfill_cloudformationstack"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="infrastructurestack",
            new_name="erieiron_in_busines_543fcf_idx",
            old_name="infrastruct_busines_19a7d5_idx",
        ),
        migrations.RenameIndex(
            model_name="infrastructurestack",
            new_name="erieiron_in_initiat_f00f62_idx",
            old_name="infrastruct_initiat_30ae5a_idx",
        ),
        migrations.AlterField(
            model_name="infrastructurestack",
            name="template_name",
            field=models.TextField(
                choices=[
                    ("infrastructure.yaml", "Infrastructure.yaml"),
                    ("infrastructure-application.yaml", "Infrastructure-application.yaml"),
                ]
            ),
        ),
    ]
