# Generated by Django 5.1.6 on 2025-10-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0067_rename_infrastruct_busines_19a7d5_idx_erieiron_in_busines_543fcf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="stack_type",
            field=models.TextField(
                choices=[("FOUNDATION", "Foundation"), ("APPLICATION", "Application")], default="asdf"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="infrastructurestack",
            name="template_name",
            field=models.TextField(choices=[("FOUNDATION", "Foundation"), ("APPLICATION", "Application")]),
        ),
    ]
