# Generated by Django 5.1.6 on 2025-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0068_infrastructurestack_stack_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="aws_env",
            field=models.TextField(choices=[("dev", "Dev"), ("production", "Production")], default="DEV"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="infrastructurestack",
            name="stack_name",
            field=models.TextField(),
        ),
    ]
