# Generated by Django 5.1.6 on 2025-10-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0069_infrastructurestack_aws_env_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructurestack",
            name="stack_id",
        ),
        migrations.AddField(
            model_name="infrastructurestack",
            name="stack_identifier",
            field=models.TextField(default="asdf"),
            preserve_default=False,
        ),
    ]
