# Generated by Django 5.1.6 on 2025-10-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0070_remove_infrastructurestack_stack_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="stack_arn",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="infrastructurestack",
            name="stack_identifier",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="infrastructurestack",
            name="stack_name",
            field=models.TextField(unique=True),
        ),
    ]
