# Generated by Django 5.1.6 on 2025-10-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0071_infrastructurestack_stack_arn_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infrastructurestack",
            old_name="stack_identifier",
            new_name="stack_namespace_token",
        ),
        migrations.RemoveField(
            model_name="initiative",
            name="cloudformation_stack_id",
        ),
        migrations.RemoveField(
            model_name="initiative",
            name="cloudformation_stack_name",
        ),
        migrations.AddField(
            model_name="business",
            name="domain_certificate_arn",
            field=models.TextField(null=True),
        ),
    ]
