# Generated by Django 5.1.6 on 2025-10-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0072_rename_stack_identifier_infrastructurestack_stack_namespace_token_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="infrastructurestack",
            name="erieiron_in_busines_543fcf_idx",
        ),
        migrations.RemoveIndex(
            model_name="infrastructurestack",
            name="erieiron_in_initiat_f00f62_idx",
        ),
        migrations.RemoveField(
            model_name="infrastructurestack",
            name="template_name",
        ),
        migrations.AddIndex(
            model_name="infrastructurestack",
            index=models.Index(fields=["business", "stack_type"], name="erieiron_in_busines_1bdd0d_idx"),
        ),
        migrations.AddIndex(
            model_name="infrastructurestack",
            index=models.Index(fields=["initiative", "stack_type"], name="erieiron_in_initiat_747370_idx"),
        ),
    ]
