# Generated by Django 5.1.6 on 2025-10-18 22:18

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0073_remove_infrastructurestack_erieiron_in_busines_543fcf_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="required_credentials",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="codeversion",
            name="code_instructions",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="llmrequest",
            name="input_messages",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="llmrequest",
            name="resp_json",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="selfdrivingtaskiteration",
            name="evaluation_json",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="selfdrivingtaskiteration",
            name="planning_json",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="selfdrivingtaskiteration",
            name="routing_json",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="selfdrivingtaskiteration",
            name="slowest_cloudformation_resources",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
    ]
