# Generated by Django 5.1.6 on 2025-10-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0074_alter_business_required_credentials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="initial_tests_pass",
            field=models.BooleanField(default=False),
        ),
    ]
