# Generated by Django 5.1.6 on 2025-10-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0075_selfdrivingtask_initial_tests_pass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selfdrivingtask",
            name="cloudformation_stack_id",
        ),
        migrations.RemoveField(
            model_name="selfdrivingtask",
            name="cloudformation_stack_name",
        ),
    ]
