# Generated by Django 5.1.6 on 2025-10-24 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0076_remove_selfdrivingtask_cloudformation_stack_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="updated_timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
