# Generated by Django 5.1.6 on 2025-10-25 00:07

import erieiron_autonomous_agent.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0077_infrastructurestack_updated_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="operation_type",
            field=models.TextField(
                choices=[
                    ("ERIE_IRON_AUTONOMOUS", "Erie iron autonomous"),
                    ("ERIE_IRON_MANUAL", "Erie iron manual"),
                    ("THIRD_PARTY_AUTONOMOUS", "Third party autonomous"),
                    ("THIRD_PARTY_MANUAL", "Third party manual"),
                ],
                default=erieiron_autonomous_agent.enums.BusinessOperationType["ERIE_IRON_AUTONOMOUS"],
            ),
        ),
    ]
