# Generated by Django 5.1.6 on 2025-10-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0078_business_operation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="green_lit",
            field=models.BooleanField(default=False),
        ),
    ]
