# Generated by Django 5.1.6 on 2025-10-25 21:11

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0079_initiative_green_lit"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="cloudformation_logs",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
    ]
