# Generated by Django 5.1.6 on 2025-12-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0080_selfdrivingtaskiteration_cloudformation_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="latest_phase_change_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="selfdrivingtask",
            name="phase_change_seq",
            field=models.IntegerField(default=0),
        ),
    ]
