# Generated by Django 5.1.6 on 2025-10-27 22:50

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0081_selfdrivingtask_phase_change_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initiative",
            name="test_file_path",
        ),
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="strategic_unblocking_json",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
    ]
