# Generated by Django 5.1.6 on 2025-10-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0082_remove_initiative_test_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="user_documentation",
            field=models.TextField(null=True),
        ),
    ]
