# Generated by Django 5.1.6 on 2025-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0083_initiative_user_documentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="debug_steps",
            field=models.TextField(null=True),
        ),
    ]
