# Generated by Django 5.1.6 on 2025-10-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0084_task_debug_steps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infrastructurestack",
            old_name="aws_env",
            new_name="env_type",
        ),
    ]
