# Generated by Django 5.1.6 on 2025-10-31 02:05

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0085_rename_aws_env_infrastructurestack_env_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="sandbox_root_dir",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="infrastructurestack",
            name="stack_vars",
            field=models.JSONField(default=dict, encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
    ]
