# Generated by Django 5.1.6 on 2025-10-31 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0086_infrastructurestack_sandbox_root_dir_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfdrivingtaskiteration",
            old_name="cloudformation_logs",
            new_name="log_content_deployment",
        ),
    ]
