# Generated by Django 5.1.6 on 2025-11-01 00:03

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0087_rename_cloudformation_logs_selfdrivingtaskiteration_log_content_deployment",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="log_content_cloudwatch",
            field=models.JSONField(encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
    ]
