# Generated by Django 5.1.6 on 2025-11-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0088_selfdrivingtaskiteration_log_content_cloudwatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtaskiteration",
            name="exceptions",
            field=models.TextField(null=True),
        ),
    ]
