# Generated by Django 5.1.6 on 2025-11-01 01:01

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0089_selfdrivingtaskiteration_exceptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="resources",
            field=models.JSONField(default=dict, encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True),
        ),
    ]
