# Generated by Django 5.1.6 on 2025-11-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0090_infrastructurestack_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="stack_configuration",
            field=models.TextField(null=True),
        ),
    ]
