# Generated by Django 5.1.6 on 2025-11-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0091_infrastructurestack_stack_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructurestack",
            name="sandbox_root_dir",
        ),
    ]
