# Generated by Django 5.1.6 on 2025-11-05 05:23

import django.db.models.deletion
import erieiron_common.enums
import erieiron_common.json_encoder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0092_remove_infrastructurestack_sandbox_root_dir",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "provider",
                    models.TextField(
                        choices=[("aws", "Aws"), ("gcp", "Gcp"), ("azure", "Azure")],
                        default=erieiron_common.enums.CloudProvider["AWS"],
                    ),
                ),
                ("account_identifier", models.TextField(blank=True, null=True)),
                ("credentials_secret_arn", models.TextField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                    ),
                ),
                ("is_default_dev", models.BooleanField(default=False)),
                ("is_default_production", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_accounts",
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_cloudaccount",
            },
        ),
        migrations.AddField(
            model_name="infrastructurestack",
            name="cloud_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stacks",
                to="erieiron_autonomous_agent.cloudaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="infrastructurestack",
            index=models.Index(
                fields=["cloud_account", "stack_type"],
                name="erieiron_in_cloud_a_65b6a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cloudaccount",
            index=models.Index(
                fields=["business", "provider"], name="erieiron_cl_busines_08e7a0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudaccount",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="cloudaccount_unique_business_name"
            ),
        ),
    ]
