# Generated by Django 5.1.6 on 2025-11-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0094_backfill_erie_iron_cloudaccount_vpc_metadata",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructurestack",
            name="stack_type",
            field=models.TextField(
                choices=[
                    ("FOUNDATION", "Foundation"),
                    ("APPLICATION", "Application"),
                    ("TARGET_ACCOUNT_BOOTSTRAP", "Target account bootstrap"),
                ]
            ),
        ),
    ]
