# Generated by Django 5.1.6 on 2025-11-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0095_alter_infrastructurestack_stack_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="niche_category",
            field=models.TextField(
                blank=True,
                help_text="Niche category used to generate this business idea (e.g., local_service_arbitrage)",
                null=True,
            ),
        ),
    ]
