# Generated by Django 5.1.6 on 2025-11-20 02:23

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0096_business_niche_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_finder_output",
            field=models.JSONField(
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True
            ),
        ),
    ]
