# Generated by Django 5.1.6 on 2025-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0097_business_business_finder_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="evaluator_output",
            field=models.TextField(null=True),
        ),
    ]
