# Generated by Django 5.1.6 on 2025-11-20 18:03

import django.db.models.deletion
import erieiron_common.json_encoder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0098_business_evaluator_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="evaluator_output",
        ),
        migrations.CreateModel(
            name="BusinessSecondOpinionEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "llm_model",
                    models.TextField(
                        choices=[
                            ("gpt-5.1", "Gpt-5.1"),
                            ("gpt-5", "Gpt-5"),
                            ("gpt-5-mini", "Gpt-5-mini"),
                            ("gpt-5-nano", "Gpt-5-nano"),
                            ("gpt-3.5-turbo", "Gpt-3.5-turbo"),
                            ("gpt-4.1", "Gpt-4.1"),
                            ("gpt-4.1-mini", "Gpt-4.1-mini"),
                            ("gpt-4.1-nano", "Gpt-4.1-nano"),
                            ("gpt-4-turbo", "Gpt-4-turbo"),
                            ("gpt-4o", "Gpt-4o"),
                            ("gpt-4o-2024-08-06", "Gpt-4o-2024-08-06"),
                            ("o3-mini-2025-01-31", "O3-mini-2025-01-31"),
                            ("o3-pro-2025-06-10", "O3-pro-2025-06-10"),
                            ("o1", "O1"),
                            ("o1-mini", "O1-mini"),
                            ("o3", "O3"),
                            ("o4", "O4"),
                            ("o4-mini", "O4-mini"),
                            ("gemini-3-pro-preview", "Gemini-3-pro-preview"),
                            ("gemini-3-flash-preview", "Gemini-3-flash-preview"),
                            (
                                "gemini-2.5-pro-preview-03-25",
                                "Gemini-2.5-pro-preview-03-25",
                            ),
                            ("gemini-2.0-flash", "Gemini-2.0-flash"),
                            (
                                "claude-sonnet-4-5-20250929",
                                "Claude-sonnet-4-5-20250929",
                            ),
                            (
                                "claude-3-7-sonnet-20250219",
                                "Claude-3-7-sonnet-20250219",
                            ),
                            (
                                "claude-3-5-sonnet-20240620",
                                "Claude-3-5-sonnet-20240620",
                            ),
                            ("claude-3-opus-20240229", "Claude-3-opus-20240229"),
                            ("deepseek-coder", "Deepseek-coder"),
                            ("deepseek-chat", "Deepseek-chat"),
                        ]
                    ),
                ),
                (
                    "evaluation",
                    models.JSONField(
                        default=dict,
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesssecondopinionevaluation",
            },
        ),
    ]
