# Generated by Django 5.1.6 on 2025-11-20 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0099_remove_business_evaluator_output_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessHumanJobDescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("estimated_hours_per_week", models.IntegerField()),
                ("job_description", models.TextField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businesshumanjobdescription",
            },
        ),
    ]
