# Generated by Django 5.1.6 on 2025-11-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0100_businesshumanjobdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="ui_design_spec",
            field=models.TextField(null=True),
        ),
    ]
