# Generated by Django 5.1.6 on 2025-11-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0101_business_ui_design_spec"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdesignrequirements",
            name="component_ids",
        ),
        migrations.RemoveField(
            model_name="taskdesignrequirements",
            name="task",
        ),
        migrations.DeleteModel(
            name="DesignComponent",
        ),
        migrations.DeleteModel(
            name="TaskDesignRequirements",
        ),
    ]
