# Generated by Django 5.1.6 on 2025-11-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0102_remove_taskdesignrequirements_component_ids_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="details",
            field=models.TextField(null=True),
        ),
    ]
