# Generated by Django 5.1.6 on 2025-11-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0103_initiative_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="creativity",
            field=models.TextField(null=True),
        ),
    ]
