# Generated by Django 5.1.6 on 2025-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0104_llmrequest_creativity"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="output_schema",
            field=models.TextField(null=True),
        ),
    ]
