# Generated by Django 5.1.6 on 2025-11-24 03:22

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0105_llmrequest_output_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="imported_shared_resources",
            field=models.JSONField(
                default=dict,
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                null=True,
            ),
        ),
    ]
