# Generated by Django 5.1.6 on 2025-11-24 21:08

import django.db.models.deletion
import erieiron_common.json_encoder
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0105_llmrequest_output_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Auto-generated summary of conversation topic"
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("led_to_change", "Led to Change"),
                        ],
                        default="active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="erieiron_autonomous_agent.business",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Scope conversation to a specific initiative",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erieiron_autonomous_agent.initiative",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_businessconversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ]
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="erieiron_autonomous_agent.businessconversation",
                    ),
                ),
                (
                    "llm_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Track API usage for this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erieiron_autonomous_agent.llmrequest",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_conversationmessage",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.TextField(
                        choices=[
                            ("business_plan", "Business Plan"),
                            ("architecture", "Architecture"),
                            ("infrastructure", "Infrastructure"),
                            ("initiative", "New Initiative"),
                            ("task", "New Task"),
                        ]
                    ),
                ),
                (
                    "change_description",
                    models.TextField(
                        help_text="Human-readable description of proposed change"
                    ),
                ),
                (
                    "change_details",
                    models.JSONField(
                        encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                        help_text="Structured details of what will change",
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="erieiron_autonomous_agent.businessconversation",
                    ),
                ),
                (
                    "resulting_tasks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tasks created to implement this change",
                        to="erieiron_autonomous_agent.task",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The assistant message that proposed this change",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erieiron_autonomous_agent.conversationmessage",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_conversationchange",
                "ordering": ["-created_at"],
            },
        ),
    ]
