# Generated by Django 5.1.6 on 2025-11-25 01:39

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0106_infrastructurestack_imported_shared_resources",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurestack",
            name="required_credentials",
            field=models.JSONField(
                default=dict,
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder,
                help_text="Stack-specific credential ARN mappings: {CredentialService.value: 'arn:...'}",
                null=True,
            ),
        ),
    ]
