# Generated by Django 5.1.6 on 2025-11-25 17:00

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0107_add_stack_required_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="credential_arns",
            field=models.JSONField(
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True
            ),
        ),
    ]
