# Generated by Django 5.1.6 on 2025-11-25 17:01

import erieiron_common.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0108_business_credential_arns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructurestack",
            name="required_credentials",
        ),
        migrations.AddField(
            model_name="infrastructurestack",
            name="credential_arns",
            field=models.JSONField(
                encoder=erieiron_common.json_encoder.ErieIronJSONEncoder, null=True
            ),
        ),
    ]
