# Generated by Django 5.1.6 on 2025-12-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0106_add_business_conversations"),
        (
            "erieiron_autonomous_agent",
            "0109_remove_infrastructurestack_required_credentials_and_more",
        ),
    ]

    operations = []
