# Generated by Django 5.1.6 on 2025-12-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0110_merge_20251213_1827"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ui_first_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UI_MOCK_API", "Ui mock api"),
                    ("SERVER_IMPLEMENTATION", "Server implementation"),
                ],
                help_text="For React/React Native projects: tracks whether this task is UI-first phase or server phase",
                max_length=50,
                null=True,
            ),
        ),
    ]
