# Generated by Django 5.1.6 on 2025-12-14 17:34

import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0111_task_ui_first_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="stack_strategy",
            field=models.TextField(
                choices=[
                    ("SINGLE_STACK", "Single stack"),
                    ("PROD_AND_DEV", "Prod and dev"),
                    ("PER_INITIATIVE", "Per initiative"),
                ],
                default=erieiron_common.enums.StackStrategy["PER_INITIATIVE"],
                help_text="Determines how infrastructure stacks are allocated for this business",
            ),
        ),
    ]
