# Generated by Django 5.1.6 on 2025-12-15 20:34

import erieiron_common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0112_business_stack_strategy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="ui_first_phase",
            new_name="implementation_phase",
        ),
        migrations.AlterField(
            model_name="business",
            name="stack_strategy",
            field=models.TextField(
                choices=[
                    ("single_stack", "Single stack"),
                    ("prod_and_dev", "Prod and dev"),
                    ("per_initiative", "Per initiative"),
                ],
                default=erieiron_common.enums.StackStrategy["PER_INITIATIVE"],
                help_text="Determines how infrastructure stacks are allocated for this business",
            ),
        ),
    ]
