# Generated by Django 5.1.6 on 2025-12-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0113_rename_ui_first_phase_task_implementation_phase_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="selfdrivingtask",
            name="iteration_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOCAL_TESTS", "Local tests"),
                    ("CONTAINER_TESTS", "Container tests"),
                    ("AWS_DEPLOYMENT", "Aws deployment"),
                ],
                default="LOCAL_TESTS",
                help_text="Current execution stage: local tests, container tests, or AWS deployment",
                max_length=50,
                null=True,
            ),
        ),
    ]
