# Generated by Django 5.1.6 on 2026-01-03 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0114_add_iteration_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="OAuth provider name (e.g., 'cognito-google')",
                        max_length=64,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Provider's unique user ID (e.g., Cognito 'sub' claim)",
                        max_length=255,
                    ),
                ),
                (
                    "raw_profile",
                    models.JSONField(
                        default=dict,
                        help_text="Raw OAuth claims/profile data from provider",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Django user linked to this OAuth account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oauth_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_oauth_account",
                "indexes": [
                    models.Index(
                        fields=["provider", "external_id"],
                        name="erieiron_oa_provide_89873d_idx",
                    ),
                    models.Index(
                        fields=["user"], name="erieiron_oa_user_id_319e4f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id"),
                        name="unique_oauth_provider_external_id",
                    )
                ],
            },
        ),
    ]
