# Generated by Django 5.1.6 on 2026-04-18 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0115_oauthaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "erieiron_workflowdefinition",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "handler_path",
                    models.TextField(
                        help_text="Dotted handler path such as package.module.function."
                    ),
                ),
                (
                    "emits_message_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("EVERY_MINUTE", "Every minute"),
                            ("EVERY_HOUR", "Every hour"),
                            ("EVERY_DAY", "Every day"),
                            ("EVERY_WEEK", "Every week"),
                            (
                                "CHAT_INTERACTION_INITIATED",
                                "Chat interaction initiated",
                            ),
                            ("CHAT_CHANNEL_LLM", "Chat channel llm"),
                            ("BUSINESS_IDEA_SUBMITTED", "Business idea submitted"),
                            (
                                "BUSINESS_JOB_DESCRIPTIONS_REQUESTED",
                                "Business job descriptions requested",
                            ),
                            ("FIND_NICHE_BUSINESS_IDEAS", "Find niche business ideas"),
                            ("ANALYSIS_REQUESTED", "Analysis requested"),
                            ("ANALYSIS_COMPLETED", "Analysis completed"),
                            ("ANALYSIS_ADDED", "Analysis added"),
                            ("BOARD_GUIDANCE_REQUESTED", "Board guidance requested"),
                            ("BOARD_GUIDANCE_UPDATED", "Board guidance updated"),
                            ("BUSINESS_GUIDANCE_UPDATED", "Business guidance updated"),
                            (
                                "BUSINESS_BOOTSTRAP_REQUESTED",
                                "Business bootstrap requested",
                            ),
                            (
                                "BUSINESS_SECOND_OPINION_EVALUATION_REQUESTED",
                                "Business second opinion evaluation requested",
                            ),
                            (
                                "PORTFOLIO_ADD_BUSINESSES_REQUESTED",
                                "Portfolio add businesses requested",
                            ),
                            (
                                "PORTFOLIO_REDUCE_BUSINESSES_REQUESTED",
                                "Portfolio reduce businesses requested",
                            ),
                            (
                                "PORTFOLIO_PICK_NEW_BUSINESS",
                                "Portfolio pick new business",
                            ),
                            (
                                "RESOURCE_PLANNING_REQUESTED",
                                "Resource planning requested",
                            ),
                            ("TASK_ASSIGNED", "Task assigned"),
                            ("TASK_UPDATED", "Task updated"),
                            ("TASK_BLOCKED", "Task blocked"),
                            ("TASK_COMPLETED", "Task completed"),
                            ("TASK_FAILED", "Task failed"),
                            ("TASK_SPEND", "Task spend"),
                            ("CEO_DIRECTIVES_ISSUED", "Ceo directives issued"),
                            (
                                "PRODUCT_INITIATIVES_REQUESTED",
                                "Product initiatives requested",
                            ),
                            (
                                "PRODUCT_INITIATIVES_DEFINED",
                                "Product initiatives defined",
                            ),
                            (
                                "INITIATIVE_DEFINITION_REQUESTED",
                                "Initiative definition requested",
                            ),
                            ("INITIATIVE_DEFINED", "Initiative defined"),
                            ("INITIATIVE_GREEN_LIT", "Initiative green lit"),
                            ("DEPLOYMENT_WORK_REQUESTED", "Deployment work requested"),
                            ("CODING_WORK_REQUESTED", "Coding work requested"),
                            ("DESIGN_WORK_REQUESTED", "Design work requested"),
                            ("HUMAN_WORK_REQUESTED", "Human work requested"),
                            (
                                "ENGINEERING_PLANNING_REQUESTED",
                                "Engineering planning requested",
                            ),
                            (
                                "BUSINESS_ARCHITECTURE_GENERATION_REQUESTED",
                                "Business architecture generation requested",
                            ),
                            (
                                "PRODUCT_PLANNING_REQUESTED",
                                "Product planning requested",
                            ),
                            (
                                "INITIATIVE_DEPLOY_REQUESTED",
                                "Initiative deploy requested",
                            ),
                            (
                                "INITIATIVE_PLANNING_REQUESTED",
                                "Initiative planning requested",
                            ),
                            (
                                "ITERATION_PLANNING_REQUESTED",
                                "Iteration planning requested",
                            ),
                            ("ITERATION_WORK_REQUESTED", "Iteration work requested"),
                            (
                                "SELF_DRIVING_CODER_REQUESTED",
                                "Self driving coder requested",
                            ),
                            (
                                "SELF_DRIVING_CODER_UPDATED",
                                "Self driving coder updated",
                            ),
                            (
                                "SELF_DRIVING_CODER_COMPLETED",
                                "Self driving coder completed",
                            ),
                            ("LLM_REQUEST", "Llm request"),
                            ("RESET_TASK_TEST", "Reset task test"),
                            (
                                "INITIATIVE_ARCHITECTURE_GENERATION_REQUESTED",
                                "Initiative architecture generation requested",
                            ),
                            (
                                "INITIATIVE_TASKS_GENERATION_REQUESTED",
                                "Initiative tasks generation requested",
                            ),
                            (
                                "INITIATIVE_USER_DOCUMENTATION_GENERATION_REQUESTED",
                                "Initiative user documentation generation requested",
                            ),
                        ],
                        help_text="Message type published after this step completes.",
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="erieiron_autonomous_agent.workflowdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_workflowstep",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.TextField(
                        choices=[
                            ("EVERY_MINUTE", "Every minute"),
                            ("EVERY_HOUR", "Every hour"),
                            ("EVERY_DAY", "Every day"),
                            ("EVERY_WEEK", "Every week"),
                            (
                                "CHAT_INTERACTION_INITIATED",
                                "Chat interaction initiated",
                            ),
                            ("CHAT_CHANNEL_LLM", "Chat channel llm"),
                            ("BUSINESS_IDEA_SUBMITTED", "Business idea submitted"),
                            (
                                "BUSINESS_JOB_DESCRIPTIONS_REQUESTED",
                                "Business job descriptions requested",
                            ),
                            ("FIND_NICHE_BUSINESS_IDEAS", "Find niche business ideas"),
                            ("ANALYSIS_REQUESTED", "Analysis requested"),
                            ("ANALYSIS_COMPLETED", "Analysis completed"),
                            ("ANALYSIS_ADDED", "Analysis added"),
                            ("BOARD_GUIDANCE_REQUESTED", "Board guidance requested"),
                            ("BOARD_GUIDANCE_UPDATED", "Board guidance updated"),
                            ("BUSINESS_GUIDANCE_UPDATED", "Business guidance updated"),
                            (
                                "BUSINESS_BOOTSTRAP_REQUESTED",
                                "Business bootstrap requested",
                            ),
                            (
                                "BUSINESS_SECOND_OPINION_EVALUATION_REQUESTED",
                                "Business second opinion evaluation requested",
                            ),
                            (
                                "PORTFOLIO_ADD_BUSINESSES_REQUESTED",
                                "Portfolio add businesses requested",
                            ),
                            (
                                "PORTFOLIO_REDUCE_BUSINESSES_REQUESTED",
                                "Portfolio reduce businesses requested",
                            ),
                            (
                                "PORTFOLIO_PICK_NEW_BUSINESS",
                                "Portfolio pick new business",
                            ),
                            (
                                "RESOURCE_PLANNING_REQUESTED",
                                "Resource planning requested",
                            ),
                            ("TASK_ASSIGNED", "Task assigned"),
                            ("TASK_UPDATED", "Task updated"),
                            ("TASK_BLOCKED", "Task blocked"),
                            ("TASK_COMPLETED", "Task completed"),
                            ("TASK_FAILED", "Task failed"),
                            ("TASK_SPEND", "Task spend"),
                            ("CEO_DIRECTIVES_ISSUED", "Ceo directives issued"),
                            (
                                "PRODUCT_INITIATIVES_REQUESTED",
                                "Product initiatives requested",
                            ),
                            (
                                "PRODUCT_INITIATIVES_DEFINED",
                                "Product initiatives defined",
                            ),
                            (
                                "INITIATIVE_DEFINITION_REQUESTED",
                                "Initiative definition requested",
                            ),
                            ("INITIATIVE_DEFINED", "Initiative defined"),
                            ("INITIATIVE_GREEN_LIT", "Initiative green lit"),
                            ("DEPLOYMENT_WORK_REQUESTED", "Deployment work requested"),
                            ("CODING_WORK_REQUESTED", "Coding work requested"),
                            ("DESIGN_WORK_REQUESTED", "Design work requested"),
                            ("HUMAN_WORK_REQUESTED", "Human work requested"),
                            (
                                "ENGINEERING_PLANNING_REQUESTED",
                                "Engineering planning requested",
                            ),
                            (
                                "BUSINESS_ARCHITECTURE_GENERATION_REQUESTED",
                                "Business architecture generation requested",
                            ),
                            (
                                "PRODUCT_PLANNING_REQUESTED",
                                "Product planning requested",
                            ),
                            (
                                "INITIATIVE_DEPLOY_REQUESTED",
                                "Initiative deploy requested",
                            ),
                            (
                                "INITIATIVE_PLANNING_REQUESTED",
                                "Initiative planning requested",
                            ),
                            (
                                "ITERATION_PLANNING_REQUESTED",
                                "Iteration planning requested",
                            ),
                            ("ITERATION_WORK_REQUESTED", "Iteration work requested"),
                            (
                                "SELF_DRIVING_CODER_REQUESTED",
                                "Self driving coder requested",
                            ),
                            (
                                "SELF_DRIVING_CODER_UPDATED",
                                "Self driving coder updated",
                            ),
                            (
                                "SELF_DRIVING_CODER_COMPLETED",
                                "Self driving coder completed",
                            ),
                            ("LLM_REQUEST", "Llm request"),
                            ("RESET_TASK_TEST", "Reset task test"),
                            (
                                "INITIATIVE_ARCHITECTURE_GENERATION_REQUESTED",
                                "Initiative architecture generation requested",
                            ),
                            (
                                "INITIATIVE_TASKS_GENERATION_REQUESTED",
                                "Initiative tasks generation requested",
                            ),
                            (
                                "INITIATIVE_USER_DOCUMENTATION_GENERATION_REQUESTED",
                                "Initiative user documentation generation requested",
                            ),
                        ]
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="erieiron_autonomous_agent.workflowdefinition",
                    ),
                ),
                (
                    "source_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="erieiron_autonomous_agent.workflowstep",
                    ),
                ),
                (
                    "target_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="erieiron_autonomous_agent.workflowstep",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_workflowconnection",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.TextField(
                        choices=[
                            ("EVERY_MINUTE", "Every minute"),
                            ("EVERY_HOUR", "Every hour"),
                            ("EVERY_DAY", "Every day"),
                            ("EVERY_WEEK", "Every week"),
                            (
                                "CHAT_INTERACTION_INITIATED",
                                "Chat interaction initiated",
                            ),
                            ("CHAT_CHANNEL_LLM", "Chat channel llm"),
                            ("BUSINESS_IDEA_SUBMITTED", "Business idea submitted"),
                            (
                                "BUSINESS_JOB_DESCRIPTIONS_REQUESTED",
                                "Business job descriptions requested",
                            ),
                            ("FIND_NICHE_BUSINESS_IDEAS", "Find niche business ideas"),
                            ("ANALYSIS_REQUESTED", "Analysis requested"),
                            ("ANALYSIS_COMPLETED", "Analysis completed"),
                            ("ANALYSIS_ADDED", "Analysis added"),
                            ("BOARD_GUIDANCE_REQUESTED", "Board guidance requested"),
                            ("BOARD_GUIDANCE_UPDATED", "Board guidance updated"),
                            ("BUSINESS_GUIDANCE_UPDATED", "Business guidance updated"),
                            (
                                "BUSINESS_BOOTSTRAP_REQUESTED",
                                "Business bootstrap requested",
                            ),
                            (
                                "BUSINESS_SECOND_OPINION_EVALUATION_REQUESTED",
                                "Business second opinion evaluation requested",
                            ),
                            (
                                "PORTFOLIO_ADD_BUSINESSES_REQUESTED",
                                "Portfolio add businesses requested",
                            ),
                            (
                                "PORTFOLIO_REDUCE_BUSINESSES_REQUESTED",
                                "Portfolio reduce businesses requested",
                            ),
                            (
                                "PORTFOLIO_PICK_NEW_BUSINESS",
                                "Portfolio pick new business",
                            ),
                            (
                                "RESOURCE_PLANNING_REQUESTED",
                                "Resource planning requested",
                            ),
                            ("TASK_ASSIGNED", "Task assigned"),
                            ("TASK_UPDATED", "Task updated"),
                            ("TASK_BLOCKED", "Task blocked"),
                            ("TASK_COMPLETED", "Task completed"),
                            ("TASK_FAILED", "Task failed"),
                            ("TASK_SPEND", "Task spend"),
                            ("CEO_DIRECTIVES_ISSUED", "Ceo directives issued"),
                            (
                                "PRODUCT_INITIATIVES_REQUESTED",
                                "Product initiatives requested",
                            ),
                            (
                                "PRODUCT_INITIATIVES_DEFINED",
                                "Product initiatives defined",
                            ),
                            (
                                "INITIATIVE_DEFINITION_REQUESTED",
                                "Initiative definition requested",
                            ),
                            ("INITIATIVE_DEFINED", "Initiative defined"),
                            ("INITIATIVE_GREEN_LIT", "Initiative green lit"),
                            ("DEPLOYMENT_WORK_REQUESTED", "Deployment work requested"),
                            ("CODING_WORK_REQUESTED", "Coding work requested"),
                            ("DESIGN_WORK_REQUESTED", "Design work requested"),
                            ("HUMAN_WORK_REQUESTED", "Human work requested"),
                            (
                                "ENGINEERING_PLANNING_REQUESTED",
                                "Engineering planning requested",
                            ),
                            (
                                "BUSINESS_ARCHITECTURE_GENERATION_REQUESTED",
                                "Business architecture generation requested",
                            ),
                            (
                                "PRODUCT_PLANNING_REQUESTED",
                                "Product planning requested",
                            ),
                            (
                                "INITIATIVE_DEPLOY_REQUESTED",
                                "Initiative deploy requested",
                            ),
                            (
                                "INITIATIVE_PLANNING_REQUESTED",
                                "Initiative planning requested",
                            ),
                            (
                                "ITERATION_PLANNING_REQUESTED",
                                "Iteration planning requested",
                            ),
                            ("ITERATION_WORK_REQUESTED", "Iteration work requested"),
                            (
                                "SELF_DRIVING_CODER_REQUESTED",
                                "Self driving coder requested",
                            ),
                            (
                                "SELF_DRIVING_CODER_UPDATED",
                                "Self driving coder updated",
                            ),
                            (
                                "SELF_DRIVING_CODER_COMPLETED",
                                "Self driving coder completed",
                            ),
                            ("LLM_REQUEST", "Llm request"),
                            ("RESET_TASK_TEST", "Reset task test"),
                            (
                                "INITIATIVE_ARCHITECTURE_GENERATION_REQUESTED",
                                "Initiative architecture generation requested",
                            ),
                            (
                                "INITIATIVE_TASKS_GENERATION_REQUESTED",
                                "Initiative tasks generation requested",
                            ),
                            (
                                "INITIATIVE_USER_DOCUMENTATION_GENERATION_REQUESTED",
                                "Initiative user documentation generation requested",
                            ),
                        ]
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "target_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="erieiron_autonomous_agent.workflowstep",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="erieiron_autonomous_agent.workflowdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "erieiron_workflowtrigger",
                "ordering": ["sort_order", "message_type"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowstep",
            index=models.Index(
                fields=["workflow", "sort_order"], name="erieiron_wo_workflo_4f1ee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstep",
            index=models.Index(
                fields=["workflow", "emits_message_type"],
                name="erieiron_wo_workflo_f16079_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstep",
            constraint=models.UniqueConstraint(
                fields=("workflow", "name"), name="uniq_workflow_step_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstep",
            constraint=models.UniqueConstraint(
                fields=("workflow", "handler_path"), name="uniq_workflow_step_handler"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowconnection",
            index=models.Index(
                fields=["workflow", "sort_order"], name="erieiron_wo_workflo_1da75c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowconnection",
            index=models.Index(
                fields=["workflow", "message_type"],
                name="erieiron_wo_workflo_b14e90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowconnection",
            index=models.Index(
                fields=["source_step", "target_step"],
                name="erieiron_wo_source__b1b3f1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowconnection",
            constraint=models.UniqueConstraint(
                fields=("workflow", "source_step", "target_step", "message_type"),
                name="uniq_workflow_connection",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtrigger",
            index=models.Index(
                fields=["workflow", "sort_order"], name="erieiron_wo_workflo_a498c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtrigger",
            index=models.Index(
                fields=["workflow", "message_type"],
                name="erieiron_wo_workflo_78c2db_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtrigger",
            constraint=models.UniqueConstraint(
                fields=("workflow", "target_step", "message_type"),
                name="uniq_workflow_trigger",
            ),
        ),
    ]
