# Generated by Django 5.1.6 on 2026-04-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "erieiron_autonomous_agent",
            "0116_workflowdefinition_workflowstep_workflowconnection_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflowstep",
            name="uniq_workflow_step_handler",
        ),
    ]
