# Generated by Django 5.1.6 on 2026-04-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0120_task_prompt_improvements"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="taskimplementationversion",
            new_name="erieiron_ta_task_id_22da9c_idx",
            old_name="erieiron_au_task_id_3998d8_idx",
        ),
        migrations.RenameIndex(
            model_name="taskimplementationversion",
            new_name="erieiron_ta_task_id_70e829_idx",
            old_name="erieiron_au_task_id_91d71b_idx",
        ),
        migrations.RenameIndex(
            model_name="taskpromptimprovement",
            new_name="erieiron_ta_task_id_9c8222_idx",
            old_name="erieiron_au_task_id_1b8c0c_idx",
        ),
        migrations.RenameIndex(
            model_name="taskpromptimprovement",
            new_name="erieiron_ta_task_id_84d21d_idx",
            old_name="erieiron_au_task_id_b64fde_idx",
        ),
    ]
