# Generated by Django 5.1.6 on 2026-04-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0122_workflow_memory_and_datastore"),
        ("erieiron_autonomous_agent", "0122_workflowdefinition_source_kind"),
    ]

    operations = []
