# Generated by Django 5.1.6 on 2026-04-19 22:26

import erieiron_autonomous_agent.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erieiron_autonomous_agent", "0123_merge_20260419_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationchange",
            name="change_type",
            field=models.TextField(
                choices=[
                    ("business_plan", "Business Plan"),
                    ("architecture", "Architecture"),
                    ("infrastructure", "Infrastructure"),
                    ("initiative", "New Initiative"),
                    ("task", "Task"),
                    ("workflow", "Workflow"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="datastore_backend",
            field=models.TextField(
                choices=[
                    ("SQLITE", "SQLite"),
                    ("POSTGRES", "Postgres"),
                    ("MONGO", "Mongo"),
                    ("DYNAMODB", "DynamoDB"),
                ],
                default=erieiron_autonomous_agent.enums.WorkflowDatastoreBackend[
                    "SQLITE"
                ],
                help_text="Backend used by the isolated workflow datastore. Defaults to SQLite inside the workflow sandbox.",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="datastore_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enables a workflow-local key-value datastore isolated from Erie Iron platform storage.",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="long_term_memory_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enables workflow-local long-term memory inside the workflow application sandbox.",
            ),
        ),
    ]
