Resources:
  WebServiceBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: WebServiceBuild
      Source:
        Type: CODECOMMIT
        Location: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/my-webservice-repo
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::123456789012:role/CodeBuildServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      BuildSpec: aws/buildspec/buildspec-webservice-base-container.yml
